import { StyleSheet, Platform, Dimensions } from 'react-native';
import { colors, semantic } from '../../theme';

const { width: screenWidth } = Dimensions.get('window');
const isMobile = screenWidth < 768;
const isMobileWeb = Platform.OS === 'web' && screenWidth < 768;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Platform.OS === 'web' ? semantic.background : '#f0f2f5',
    position: 'relative',
  },
  // Background Decorative Elements
  backgroundContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0,
    overflow: 'hidden',
  },
  backgroundGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Platform.OS === 'web' ? semantic.background : '#f0f2f5',
  },
  backgroundCircle1: {
    position: 'absolute',
    width: Platform.OS === 'web' ? 600 : 400,
    height: Platform.OS === 'web' ? 600 : 400,
    borderRadius: Platform.OS === 'web' ? 300 : 200,
    backgroundColor: 'rgba(79, 70, 229, 0.08)',
    top: Platform.OS === 'web' ? -200 : -150,
    right: Platform.OS === 'web' ? -200 : -150,
    ...(Platform.OS === 'web' ? {
      filter: 'blur(80px)',
    } : {}),
  },
  backgroundCircle2: {
    position: 'absolute',
    width: Platform.OS === 'web' ? 500 : 350,
    height: Platform.OS === 'web' ? 500 : 350,
    borderRadius: Platform.OS === 'web' ? 250 : 175,
    backgroundColor: 'rgba(139, 92, 246, 0.06)',
    bottom: Platform.OS === 'web' ? -150 : -100,
    left: Platform.OS === 'web' ? -150 : -100,
    ...(Platform.OS === 'web' ? {
      filter: 'blur(70px)',
    } : {}),
  },
  backgroundCircle3: {
    position: 'absolute',
    width: Platform.OS === 'web' ? 400 : 300,
    height: Platform.OS === 'web' ? 400 : 300,
    borderRadius: Platform.OS === 'web' ? 200 : 150,
    backgroundColor: 'rgba(59, 130, 246, 0.05)',
    top: Platform.OS === 'web' ? '40%' : '35%',
    right: Platform.OS === 'web' ? '10%' : '5%',
    ...(Platform.OS === 'web' ? {
      filter: 'blur(60px)',
    } : {}),
  },
  scrollView: {
    flex: 1,
    zIndex: 1,
  },
  scrollContent: {
    paddingTop: Platform.OS === 'web' ? 24 : 20,
    paddingBottom: Platform.OS === 'web' ? 48 : 80,
    flexGrow: 1,
    backgroundColor: 'transparent',
    width: '100%',
  },
  // Modern Hero Section - Improved Contrast & UX with Background Pattern
  heroSection: {
    backgroundColor: semantic.primary,
    paddingTop: Platform.OS === 'web' ? 60 : 40,
    paddingBottom: Platform.OS === 'web' ? 70 : 50,
    paddingHorizontal: Platform.OS === 'web' ? 20 : 20,
    marginBottom: Platform.OS === 'web' ? 40 : 30,
    position: 'relative',
    overflow: 'hidden',
    ...(Platform.OS === 'web' ? {
      backgroundImage: `
        linear-gradient(135deg, ${semantic.primary} 0%, #5b21b6 50%, #7c3aed 100%),
        radial-gradient(circle at 20% 50%, rgba(255, 255, 255, 0.1) 0%, transparent 50%),
        radial-gradient(circle at 80% 80%, rgba(255, 255, 255, 0.08) 0%, transparent 50%)
      `,
    } : {
      backgroundColor: semantic.primary,
    }),
  },
  heroContent: {
    width: '100%',
    position: 'relative',
    zIndex: 1,
  },
  heroTitle: {
    fontSize: Platform.OS === 'web' ? (isMobileWeb ? 28 : 42) : 28,
    fontWeight: '800',
    color: semantic.surface, // High contrast: 12.6:1 ratio on #4f46e5
    marginBottom: Platform.OS === 'web' ? (isMobileWeb ? 8 : 12) : 8,
    lineHeight: Platform.OS === 'web' ? (isMobileWeb ? 36 : 52) : 36,
    ...(Platform.OS === 'web' ? {
      letterSpacing: -0.5,
      textShadow: '0 2px 8px rgba(0, 0, 0, 0.2)',
    } : {
      textShadowColor: 'rgba(0, 0, 0, 0.2)',
      textShadowOffset: { width: 0, height: 2 },
      textShadowRadius: 4,
    }),
  },
  heroSubtitle: {
    fontSize: Platform.OS === 'web' ? (isMobileWeb ? 16 : 20) : 16,
    color: semantic.surface, // Changed to pure white for maximum contrast (was #f8fafc)
    marginBottom: Platform.OS === 'web' ? (isMobileWeb ? 20 : 32) : 24,
    fontWeight: '600',
    lineHeight: Platform.OS === 'web' ? (isMobileWeb ? 24 : 28) : 24,
    ...(Platform.OS === 'web' ? {
      textShadow: '0 1px 4px rgba(0, 0, 0, 0.15)',
    } : {
      textShadowColor: 'rgba(0, 0, 0, 0.15)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    }),
  },
  modernSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? (isMobileWeb ? 12 : 16) : 14,
    paddingHorizontal: Platform.OS === 'web' ? (isMobileWeb ? 12 : 20) : 16,
    paddingVertical: Platform.OS === 'web' ? (isMobileWeb ? 2 : 4) : 4,
    borderWidth: Platform.OS === 'web' ? (isMobileWeb ? 1 : 2) : 2,
    borderColor: semantic.border,
    ...(Platform.OS === 'web' ? {
      boxShadow: isMobileWeb ? '0 2px 8px rgba(0, 0, 0, 0.1)' : '0 10px 40px rgba(0, 0, 0, 0.15), 0 4px 12px rgba(0, 0, 0, 0.1)',
      transition: 'all 0.2s ease',
      position: 'relative' as any,
      zIndex: 1,
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 8,
    }),
  },
  searchIconContainer: {
    marginRight: Platform.OS === 'web' ? (isMobileWeb ? 8 : 12) : 10,
  },
  modernSearchInput: {
    flex: 1,
    fontSize: Platform.OS === 'web' ? (isMobileWeb ? 14 : 16) : 15,
    color: '#0f172a', // High contrast: 15.8:1 on white
    paddingVertical: Platform.OS === 'web' ? (isMobileWeb ? 10 : 14) : 12,
    fontWeight: '500',
    lineHeight: Platform.OS === 'web' ? (isMobileWeb ? 20 : 24) : 22,
    minWidth: 0, // Allow text input to shrink on mobile
  },
  modernSearchButton: {
    backgroundColor: semantic.primary, // Darker for better contrast
    paddingHorizontal: Platform.OS === 'web' ? (isMobileWeb ? 16 : 24) : 20,
    paddingVertical: Platform.OS === 'web' ? (isMobileWeb ? 10 : 12) : 10,
    borderRadius: Platform.OS === 'web' ? (isMobileWeb ? 10 : 12) : 10,
    marginLeft: Platform.OS === 'web' ? (isMobileWeb ? 6 : 0) : 0,
    ...(Platform.OS === 'web' ? {
      transition: 'all 0.2s ease',
      cursor: 'pointer',
      boxShadow: isMobileWeb ? `0 2px 6px rgba(79, 70, 229, 0.3)` : `0 4px 12px rgba(79, 70, 229, 0.4)`,
      userSelect: 'none' as any,
      WebkitUserSelect: 'none' as any,
      zIndex: 10,
      position: 'relative' as any,
    } : {
      shadowColor: semantic.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 4,
    }),
  },
  modernSearchButtonText: {
    color: semantic.surface, // High contrast: 12.6:1 on #4f46e5
    fontSize: Platform.OS === 'web' ? (isMobileWeb ? 13 : 15) : 14,
    fontWeight: '700',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: Platform.OS === 'web' ? 40 : 20,
    marginTop: Platform.OS === 'web' ? 20 : 10,
    marginBottom: Platform.OS === 'web' ? 30 : 20,
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? 16 : 25,
    paddingHorizontal: Platform.OS === 'web' ? 24 : 20,
    paddingVertical: Platform.OS === 'web' ? 16 : 12,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 2px 8px rgba(0, 0, 0, 0.06), 0 1px 3px rgba(0, 0, 0, 0.04)',
      borderWidth: 1,
      borderColor: semantic.border,
    } : {
      ...((Platform.OS as string) !== 'web' && {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
      }),
    }),
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#333',
  },
  searchButton: {
    padding: 8,
  },
  searchIcon: {
    fontSize: 20,
    color: semantic.primary,
  },
  welcomeContainer: {
    paddingHorizontal: Platform.OS === 'web' ? 20 : 20,
    marginBottom: Platform.OS === 'web' ? 35 : 25,
    marginTop: Platform.OS === 'web' ? 10 : 0,
  },
  welcomeTitle: {
    fontSize: Platform.OS === 'web' ? 32 : 24,
    fontWeight: 'bold',
    color: semantic.textPrimary,
    marginBottom: Platform.OS === 'web' ? 8 : 5,
    ...(Platform.OS === 'web' ? {
      letterSpacing: -0.5,
    } : {}),
  },
  welcomeSubtitle: {
    fontSize: Platform.OS === 'web' ? 18 : 16,
    color: semantic.textSecondary,
    ...(Platform.OS === 'web' ? {
      letterSpacing: 0.2,
    } : {}),
  },
  loadingContainer: {
    padding: 40,
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    color: semantic.textSecondary,
  },
  quickActionsContainer: {
    paddingHorizontal: 20,
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: Platform.OS === 'web' ? (isMobileWeb ? 24 : 28) : 26,
    fontWeight: Platform.OS === 'web' ? '800' : '900',
    color: '#0f172a', // Higher contrast: 15.8:1 on light background (was #1e293b - 12.6:1)
    marginBottom: Platform.OS === 'web' ? (isMobileWeb ? 20 : 24) : 22,
    marginTop: Platform.OS === 'web' ? 0 : 8,
    paddingBottom: Platform.OS === 'web' ? (isMobileWeb ? 14 : 16) : 14,
    borderBottomWidth: Platform.OS === 'web' ? (isMobileWeb ? 2 : 3) : 4,
    borderBottomColor: semantic.primary,
    alignSelf: 'flex-start',
    paddingRight: Platform.OS === 'web' ? (isMobileWeb ? 20 : 24) : 24,
    paddingLeft: Platform.OS === 'web' ? 0 : 4,
    ...(Platform.OS === 'web' ? {
      letterSpacing: -0.5,
    } : {
      letterSpacing: -0.4,
      textShadowColor: 'rgba(0, 0, 0, 0.1)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    }),
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  quickActionButton: {
    width: (screenWidth - 60) / 2,
    backgroundColor: semantic.surface,
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    marginBottom: 15,
    position: 'relative',
  },
  quickActionIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  quickActionText: {
    fontSize: 14,
    fontWeight: '600',
    color: semantic.textPrimary,
  },
  badge: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: semantic.error,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    paddingHorizontal: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    color: semantic.surface,
    fontSize: 12,
    fontWeight: 'bold',
  },
  categoriesContainer: {
    marginBottom: Platform.OS === 'web' ? 48 : 40,
    marginTop: Platform.OS === 'web' ? 32 : 28,
    paddingHorizontal: Platform.OS === 'web' ? 24 : 24,
    paddingVertical: Platform.OS === 'web' ? 32 : 28,
    paddingTop: Platform.OS === 'web' ? 32 : 28,
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? 20 : 18,
    marginHorizontal: Platform.OS === 'web' ? 24 : 16,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 16px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.04)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 4,
      borderWidth: 1,
      borderColor: semantic.border,
    }),
  },
  categoriesScrollView: {
    paddingLeft: 20,
  },
  categoriesScrollContent: {
    paddingRight: 20,
  },
  // Banner Slider Styles
  bannerContainer: {
    marginBottom: Platform.OS === 'web' ? 32 : 28,
    marginTop: Platform.OS === 'web' ? 24 : 24,
    marginHorizontal: Platform.OS === 'web' ? 24 : 16,
    paddingVertical: Platform.OS === 'web' ? 0 : 8,
  },
  bannerHeader: {
    marginBottom: Platform.OS === 'web' ? 20 : 20,
    marginTop: Platform.OS === 'web' ? 0 : 8,
    paddingHorizontal: Platform.OS === 'web' ? 0 : 4,
  },
  bannerTitle: {
    fontSize: Platform.OS === 'web' ? 26 : 24,
    fontWeight: Platform.OS === 'web' ? '800' : '900',
    color: semantic.textPrimary,
    paddingBottom: Platform.OS === 'web' ? 12 : 12,
    borderBottomWidth: Platform.OS === 'web' ? 3 : 4,
    borderBottomColor: semantic.primary,
    alignSelf: 'flex-start',
    paddingRight: Platform.OS === 'web' ? 24 : 24,
    paddingLeft: Platform.OS === 'web' ? 0 : 4,
    letterSpacing: Platform.OS === 'web' ? -0.5 : -0.4,
    ...(Platform.OS !== 'web' ? {
      textShadowColor: 'rgba(0, 0, 0, 0.1)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    } : {}),
  },
  bannerScrollView: {
    borderRadius: Platform.OS === 'web' ? 20 : 16,
    overflow: 'hidden',
  },
  bannerScrollContent: {
    paddingHorizontal: 0,
  },
  bannerSlide: {
    width: screenWidth - (Platform.OS === 'web' ? 48 : 32),
    marginRight: Platform.OS === 'web' ? 0 : 0,
  },
  bannerCard: {
    width: '100%',
    height: Platform.OS === 'web' ? 400 : 320,
    borderRadius: Platform.OS === 'web' ? 20 : 16,
    overflow: 'hidden',
    position: 'relative',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.15), 0 4px 8px rgba(0, 0, 0, 0.1)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 8,
    }),
  },
  bannerImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  bannerImagePlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: semantic.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bannerImageIcon: {
    fontSize: 80,
  },
  bannerOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '60%',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  bannerContent: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: Platform.OS === 'web' ? 24 : 20,
    zIndex: 2,
  },
  bannerBadgesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Platform.OS === 'web' ? 8 : 6,
    marginBottom: Platform.OS === 'web' ? 12 : 10,
    flexWrap: 'wrap',
  },
  bannerBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFD700',
    paddingHorizontal: Platform.OS === 'web' ? 12 : 10,
    paddingVertical: Platform.OS === 'web' ? 6 : 5,
    borderRadius: Platform.OS === 'web' ? 20 : 16,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 2px 8px rgba(255, 215, 0, 0.4)',
    } : {
      shadowColor: '#FFD700',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 3,
    }),
  },
  bannerBadgeText: {
    color: semantic.textPrimary,
    fontSize: Platform.OS === 'web' ? 12 : 11,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  bannerServiceName: {
    fontSize: Platform.OS === 'web' ? 28 : 24,
    fontWeight: '800',
    color: semantic.surface,
    marginBottom: Platform.OS === 'web' ? 8 : 6,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  bannerProviderName: {
    fontSize: Platform.OS === 'web' ? 16 : 14,
    fontWeight: '600',
    color: semantic.border,
    marginBottom: Platform.OS === 'web' ? 12 : 10,
  },
  bannerRating: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Platform.OS === 'web' ? 12 : 10,
    gap: 8,
  },
  bannerRatingText: {
    fontSize: Platform.OS === 'web' ? 16 : 14,
    fontWeight: '700',
    color: '#FFD700',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  bannerReviewCount: {
    fontSize: Platform.OS === 'web' ? 14 : 12,
    color: semantic.border,
  },
  bannerPrice: {
    fontSize: Platform.OS === 'web' ? 24 : 20,
    fontWeight: '800',
    color: semantic.surface,
    marginBottom: Platform.OS === 'web' ? 16 : 14,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  bannerActions: {
    flexDirection: 'row',
    gap: Platform.OS === 'web' ? 12 : 10,
  },
  bannerViewButton: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: Platform.OS === 'web' ? 12 : 10,
    paddingHorizontal: Platform.OS === 'web' ? 20 : 16,
    borderRadius: Platform.OS === 'web' ? 12 : 10,
    borderWidth: 2,
    borderColor: semantic.surface,
    alignItems: 'center',
    ...(Platform.OS === 'web' ? {
      transition: 'all 0.3s ease',
      cursor: 'pointer',
    } : {}),
  },
  bannerViewButtonText: {
    color: semantic.surface,
    fontSize: Platform.OS === 'web' ? 14 : 13,
    fontWeight: '700',
  },
  bannerBookButton: {
    flex: 1,
    backgroundColor: semantic.primary,
    paddingVertical: Platform.OS === 'web' ? 12 : 10,
    paddingHorizontal: Platform.OS === 'web' ? 20 : 16,
    borderRadius: Platform.OS === 'web' ? 12 : 10,
    alignItems: 'center',
    ...(Platform.OS === 'web' ? {
      boxShadow: `0 4px 12px rgba(74, 85, 225, 0.4)`,
      transition: 'all 0.3s ease',
      cursor: 'pointer',
    } : {
      shadowColor: semantic.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    }),
  },
  bannerBookButtonText: {
    color: semantic.surface,
    fontSize: Platform.OS === 'web' ? 14 : 13,
    fontWeight: '700',
  },
  bannerPagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: Platform.OS === 'web' ? 16 : 12,
    gap: 8,
  },
  bannerDot: {
    width: Platform.OS === 'web' ? 10 : 8,
    height: Platform.OS === 'web' ? 10 : 8,
    borderRadius: Platform.OS === 'web' ? 5 : 4,
    backgroundColor: colors.neutral[300],
    ...(Platform.OS === 'web' ? {
      transition: 'all 0.3s ease',
    } : {}),
  },
  bannerDotActive: {
    width: Platform.OS === 'web' ? 24 : 20,
    backgroundColor: semantic.primary,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 2px 8px rgba(74, 85, 225, 0.4)',
    } : {}),
  },
  // Modern Category Cards (matching service card style)
  modernCategoryCard: {
    width: Platform.OS === 'web' ? 320 : 280,
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? 16 : 14,
    overflow: 'hidden',
    marginRight: Platform.OS === 'web' ? 20 : 16,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 16px rgba(0, 0, 0, 0.08), 0 2px 6px rgba(0, 0, 0, 0.04)',
      borderWidth: 1,
      borderColor: colors.neutral[100],
      transition: 'all 0.3s ease',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 4,
    }),
  },
  modernCategoryImageContainer: {
    width: '100%',
    height: Platform.OS === 'web' ? 180 : 160,
    position: 'relative',
    backgroundColor: colors.neutral[100],
  },
  modernCategoryImage: {
    width: '100%',
    height: '100%',
  },
  modernCategoryImagePlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.neutral[100],
  },
  categoryEmoji: {
    fontSize: Platform.OS === 'web' ? 64 : 56,
  },
  categoryCountBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: semantic.primary,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    ...(Platform.OS === 'web' ? {
      boxShadow: `0 4px 12px rgba(79, 70, 229, 0.4)`,
    } : {
      shadowColor: semantic.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 4,
    }),
  },
  categoryCountBadgeText: {
    color: semantic.surface,
    fontSize: Platform.OS === 'web' ? 12 : 11,
    fontWeight: '700',
  },
  modernCategoryInfo: {
    padding: Platform.OS === 'web' ? 20 : 16,
  },
  modernCategoryTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: Platform.OS === 'web' ? 8 : 6,
    gap: Platform.OS === 'web' ? 8 : 6,
  },
  modernCategoryTitle: {
    fontSize: Platform.OS === 'web' ? 20 : 18,
    fontWeight: '800',
    color: '#0f172a',
    flex: 1,
    letterSpacing: -0.5,
    lineHeight: Platform.OS === 'web' ? 26 : 24,
  },
  modernCategoryMeta: {
    marginBottom: Platform.OS === 'web' ? 14 : 12,
  },
  modernCategoryCountText: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: colors.neutral[600],
    fontWeight: '600',
  },
  modernCategoryActions: {
    flexDirection: 'row',
    paddingHorizontal: Platform.OS === 'web' ? 20 : 16,
    paddingBottom: Platform.OS === 'web' ? 20 : 16,
  },
  modernCategoryViewButton: {
    flex: 1,
    backgroundColor: semantic.primary,
    paddingVertical: Platform.OS === 'web' ? 14 : 12,
    borderRadius: Platform.OS === 'web' ? 12 : 10,
    alignItems: 'center',
    ...(Platform.OS === 'web' ? {
      boxShadow: `0 4px 12px rgba(79, 70, 229, 0.4)`,
      transition: 'all 0.2s ease',
      cursor: 'pointer',
    } : {
      shadowColor: semantic.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 4,
    }),
  },
  modernCategoryViewButtonText: {
    color: semantic.surface,
    fontSize: Platform.OS === 'web' ? 15 : 14,
    fontWeight: '700',
  },
  categoryCard: {
    width: Platform.OS === 'web' ? 140 : 120,
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? 16 : 12,
    padding: Platform.OS === 'web' ? 20 : 15,
    alignItems: 'center',
    marginRight: Platform.OS === 'web' ? 20 : 15,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 2px 8px rgba(0, 0, 0, 0.06), 0 1px 3px rgba(0, 0, 0, 0.04)',
      borderWidth: 1,
      borderColor: '#F1F3F5',
      transition: 'all 0.2s ease',
      cursor: 'pointer',
    } : {
      ...((Platform.OS as string) !== 'web' && {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
      }),
    }),
  },
  categoryIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  categoryLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: semantic.textPrimary,
    textAlign: 'center',
    marginBottom: 4,
  },
  categoryCount: {
    fontSize: 11,
    color: semantic.textSecondary,
  },
  servicesContainer: {
    marginBottom: Platform.OS === 'web' ? (isMobileWeb ? 32 : 48) : 40,
    marginTop: Platform.OS === 'web' ? (isMobileWeb ? 24 : 32) : 28,
    paddingHorizontal: Platform.OS === 'web' ? (isMobileWeb ? 16 : 24) : 24,
    paddingVertical: Platform.OS === 'web' ? (isMobileWeb ? 20 : 32) : 28,
    paddingTop: Platform.OS === 'web' ? (isMobileWeb ? 20 : 32) : 28,
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? (isMobileWeb ? 16 : 20) : 18,
    marginHorizontal: Platform.OS === 'web' ? (isMobileWeb ? 16 : 24) : 16,
    overflow: 'hidden',
    ...(Platform.OS === 'web' ? {
      boxShadow: isMobileWeb
        ? '0 2px 8px rgba(0, 0, 0, 0.06), 0 1px 2px rgba(0, 0, 0, 0.04)'
        : '0 4px 16px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.04)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 4,
      borderWidth: 1,
      borderColor: semantic.border,
    }),
  },
  seeAllText: {
    fontSize: 14,
    color: semantic.primary,
    fontWeight: '600',
  },
  servicesScrollView: {
    paddingLeft: 20,
  },
  servicesScrollContent: {
    paddingRight: 20,
  },
  // Modern Service Cards
  modernServiceCard: {
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? (isMobileWeb ? 16 : 20) : 18,
    marginRight: Platform.OS === 'web' ? 0 : 0,
    marginBottom: Platform.OS === 'web' ? 0 : 16,
    width: Platform.OS === 'web'
      ? (isMobileWeb ? '100%' : ('calc(25% - 18px)' as any))
      : '100%', // Full width on mobile web, 4 columns on desktop
    overflow: 'hidden',
    ...(Platform.OS === 'web' ? {
      boxShadow: isMobileWeb
        ? '0 4px 12px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.04)'
        : '0 8px 24px rgba(0, 0, 0, 0.1), 0 4px 8px rgba(0, 0, 0, 0.06)',
      borderWidth: 1,
      borderColor: colors.neutral[100],
      transition: 'all 0.3s ease',
      cursor: 'pointer',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.1,
      shadowRadius: 16,
      elevation: 8,
    }),
  },
  modernServiceImageContainer: {
    width: '100%',
    height: Platform.OS === 'web' ? (isMobileWeb ? 180 : 200) : 220,
    backgroundColor: semantic.background,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  modernServiceImage: {
    width: '100%',
    height: '100%',
  },
  modernServiceImagePlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.neutral[100],
  },
  featuredBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: semantic.success,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 12px rgba(16, 185, 129, 0.4)',
    } : {
      shadowColor: semantic.success,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 4,
    }),
  },
  featuredBadgeText: {
    color: semantic.surface,
    fontSize: Platform.OS === 'web' ? 12 : 11,
    fontWeight: '700',
  },
  modernServiceInfo: {
    padding: Platform.OS === 'web' ? (isMobileWeb ? 16 : 20) : 16,
  },
  modernServiceTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: Platform.OS === 'web' ? (isMobileWeb ? 6 : 8) : 6,
    gap: Platform.OS === 'web' ? (isMobileWeb ? 6 : 8) : 6,
  },
  modernServiceTitle: {
    fontSize: Platform.OS === 'web' ? (isMobileWeb ? 18 : 20) : 18,
    fontWeight: '800',
    color: '#0f172a', // Higher contrast: 15.8:1 on white (was #1e293b - 12.6:1)
    flex: 1,
    letterSpacing: -0.5,
    lineHeight: Platform.OS === 'web' ? (isMobileWeb ? 24 : 26) : 24,
  },
  modernServiceProvider: {
    fontSize: Platform.OS === 'web' ? (isMobileWeb ? 13 : 14) : 13,
    color: colors.neutral[600], // Better contrast: 7.4:1 on white (was #64748b - 5.2:1)
    marginBottom: Platform.OS === 'web' ? (isMobileWeb ? 10 : 12) : 10,
    fontWeight: '600', // Increased for better readability
  },
  modernServiceMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Platform.OS === 'web' ? (isMobileWeb ? 12 : 14) : 12,
  },
  modernRatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: semantic.warningLight,
    paddingHorizontal: Platform.OS === 'web' ? 12 : 10,
    paddingVertical: Platform.OS === 'web' ? 6 : 5,
    borderRadius: Platform.OS === 'web' ? 20 : 18,
    alignSelf: 'flex-start',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    }),
  },
  modernRatingStar: {
    fontSize: Platform.OS === 'web' ? 16 : 14,
    marginRight: 4,
  },
  modernRatingText: {
    fontSize: Platform.OS === 'web' ? 15 : 14,
    fontWeight: '700',
    color: '#78350F',
    marginRight: 4,
  },
  modernReviewCount: {
    fontSize: Platform.OS === 'web' ? 13 : 12,
    color: '#78350F',
    fontWeight: '600',
  },
  newBadge: {
    backgroundColor: semantic.warningLight,
    color: '#92400e',
    fontSize: Platform.OS === 'web' ? 12 : 11,
    fontWeight: '700',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  modernLocationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginLeft: 8,
  },
  modernLocationIcon: {
    fontSize: Platform.OS === 'web' ? 14 : 12,
    marginRight: 4,
  },
  modernLocationText: {
    fontSize: Platform.OS === 'web' ? 13 : 12,
    color: colors.neutral[600], // Better contrast: 7.4:1 (was #64748b - 5.2:1)
    fontWeight: '600', // Increased for readability
    flex: 1,
    flexWrap: 'wrap',
  },
  modernDistanceText: {
    fontSize: Platform.OS === 'web' ? 13 : 12,
    color: colors.success[600], // Darker green for better contrast: 4.8:1 (was #10b981 - 3.1:1)
    fontWeight: '700',
    marginLeft: 4,
  },
  modernPriceContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: Platform.OS === 'web' ? (isMobileWeb ? 14 : 16) : 14,
    paddingTop: Platform.OS === 'web' ? (isMobileWeb ? 10 : 12) : 10,
    borderTopWidth: 1,
    borderTopColor: colors.neutral[100],
  },
  modernPriceLabel: {
    fontSize: Platform.OS === 'web' ? (isMobileWeb ? 11 : 12) : 11,
    color: colors.neutral[600], // Better contrast: 7.4:1 (was #64748b - 5.2:1)
    fontWeight: '600', // Increased for readability
    marginRight: 6,
  },
  modernPrice: {
    fontSize: Platform.OS === 'web' ? (isMobileWeb ? 22 : 24) : 22,
    fontWeight: '800',
    color: semantic.primary, // Darker blue for better contrast: 7.1:1 on white (was #4a55e1 - 6.2:1)
    letterSpacing: -0.5,
  },
  modernServiceActions: {
    flexDirection: 'row',
    paddingHorizontal: Platform.OS === 'web' ? (isMobileWeb ? 16 : 20) : 16,
    paddingBottom: Platform.OS === 'web' ? (isMobileWeb ? 16 : 20) : 16,
    gap: Platform.OS === 'web' ? (isMobileWeb ? 10 : 12) : 10,
  },
  modernViewButton: {
    flex: 1,
    backgroundColor: semantic.background,
    paddingVertical: Platform.OS === 'web' ? (isMobileWeb ? 12 : 14) : 12,
    borderRadius: Platform.OS === 'web' ? (isMobileWeb ? 10 : 12) : 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: semantic.border,
    ...(Platform.OS === 'web' ? {
      transition: 'all 0.2s ease',
      cursor: 'pointer',
    } : {}),
  },
  modernViewButtonText: {
    color: colors.neutral[700], // Better contrast: 9.5:1 on light gray (was #475569)
    fontSize: Platform.OS === 'web' ? (isMobileWeb ? 14 : 15) : 14,
    fontWeight: '700',
  },
  modernBookButton: {
    flex: 1,
    backgroundColor: semantic.primary, // Darker for better contrast
    paddingVertical: Platform.OS === 'web' ? (isMobileWeb ? 12 : 14) : 12,
    borderRadius: Platform.OS === 'web' ? (isMobileWeb ? 10 : 12) : 10,
    alignItems: 'center',
    ...(Platform.OS === 'web' ? {
      boxShadow: isMobileWeb
        ? `0 2px 6px rgba(79, 70, 229, 0.3)`
        : `0 4px 12px rgba(79, 70, 229, 0.4)`,
      transition: 'all 0.2s ease',
      cursor: 'pointer',
    } : {
      shadowColor: semantic.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 4,
    }),
  },
  modernBookButtonText: {
    color: semantic.surface, // High contrast: 12.6:1 on #4f46e5
    fontSize: Platform.OS === 'web' ? (isMobileWeb ? 14 : 15) : 14,
    fontWeight: '700',
  },
  modernProfileButton: {
    flex: 1,
    backgroundColor: semantic.success,
    paddingVertical: Platform.OS === 'web' ? 14 : 12,
    borderRadius: Platform.OS === 'web' ? 12 : 10,
    alignItems: 'center',
    marginHorizontal: Platform.OS === 'web' ? 6 : 5,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 12px rgba(16, 185, 129, 0.4)',
      transition: 'all 0.2s ease',
      cursor: 'pointer',
    } : {
      shadowColor: semantic.success,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 4,
    }),
  },
  modernProfileButtonText: {
    color: semantic.surface,
    fontSize: Platform.OS === 'web' ? 15 : 14,
    fontWeight: '700',
  },
  serviceCard: {
    backgroundColor: semantic.surface,
    borderRadius: 16,
    padding: 0,
    marginRight: 15,
    width: 280,
    overflow: 'hidden',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.04)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 6,
    }),
  },
  serviceCardGrid: {
    width: '100%',
    marginRight: 0,
  },
  serviceImageContainer: {
    width: '100%',
    height: 160,
    backgroundColor: '#1a1a1a',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  serviceImage: {
    width: '100%',
    height: '100%',
  },
  serviceEmoji: {
    fontSize: 56,
  },
  serviceInfo: {
    padding: 16,
    paddingBottom: 12,
  },
  serviceTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
    gap: 8,
  },
  serviceTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1a1a',
    flex: 1,
    letterSpacing: -0.3,
  },
  serviceProvider: {
    fontSize: 14,
    color: semantic.textSecondary,
    marginBottom: 8,
    fontWeight: '500',
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    backgroundColor: semantic.warningLight,
    paddingHorizontal: Platform.OS === 'web' ? 12 : 10,
    paddingVertical: Platform.OS === 'web' ? 6 : 5,
    borderRadius: Platform.OS === 'web' ? 20 : 18,
    alignSelf: 'flex-start',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    }),
  },
  ratingText: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: '#78350F',
    marginRight: 4,
    fontWeight: '700',
  },
  reviewCount: {
    fontSize: Platform.OS === 'web' ? 13 : 12,
    color: '#78350F',
    fontWeight: '600',
  },
  servicePrice: {
    fontSize: 20,
    fontWeight: '700',
    color: '#4285F4',
    marginBottom: 6,
    letterSpacing: -0.5,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  serviceLocation: {
    fontSize: 13,
    color: semantic.textSecondary,
    fontWeight: '500',
    flexWrap: 'wrap',
  },
  distanceText: {
    fontSize: 13,
    color: semantic.success,
    fontWeight: '600',
  },
  serviceActions: {
    flexDirection: 'row',
    paddingHorizontal: isMobile ? 12 : 16,
    paddingBottom: isMobile ? 12 : 16,
    gap: isMobile ? 8 : 10,
  },
  viewDetailsButton: {
    flex: 1,
    backgroundColor: semantic.surface,
    paddingVertical: isMobile ? 16 : 14,
    paddingHorizontal: isMobile ? 12 : 16,
    borderRadius: isMobile ? 10 : 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: isMobile ? 1.5 : 1.5,
    borderColor: '#4285F4',
    minHeight: isMobile ? 48 : undefined,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 2px 4px rgba(66, 133, 244, 0.1)',
    } : {
      shadowColor: '#4285F4',
      shadowOffset: { width: 0, height: isMobile ? 2 : 2 },
      shadowOpacity: isMobile ? 0.15 : 0.1,
      shadowRadius: isMobile ? 6 : 4,
      elevation: isMobile ? 3 : 2,
    }),
  },
  viewDetailsButtonText: {
    color: '#4285F4',
    fontSize: isMobile ? 14 : 15,
    fontWeight: '700',
    letterSpacing: isMobile ? 0.3 : 0.2,
  },
  bookNowButton: {
    flex: 1,
    backgroundColor: '#4285F4',
    paddingVertical: isMobile ? 16 : 14,
    paddingHorizontal: isMobile ? 12 : 16,
    borderRadius: isMobile ? 10 : 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: isMobile ? 48 : undefined,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 12px rgba(66, 133, 244, 0.3), 0 2px 4px rgba(66, 133, 244, 0.2)',
    } : {
      shadowColor: '#4285F4',
      shadowOffset: { width: 0, height: isMobile ? 4 : 4 },
      shadowOpacity: isMobile ? 0.35 : 0.3,
      shadowRadius: isMobile ? 10 : 8,
      elevation: isMobile ? 5 : 4,
    }),
  },
  bookNowButtonText: {
    color: semantic.surface,
    fontSize: isMobile ? 14 : 15,
    fontWeight: '700',
    letterSpacing: isMobile ? 0.3 : 0.2,
  },
  profileButtonAction: {
    flex: 1,
    backgroundColor: semantic.success,
    paddingVertical: isMobile ? 16 : 14,
    paddingHorizontal: isMobile ? 12 : 16,
    borderRadius: isMobile ? 10 : 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: isMobile ? 48 : undefined,
    marginHorizontal: isMobile ? 4 : 5,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 12px rgba(16, 185, 129, 0.3), 0 2px 4px rgba(16, 185, 129, 0.2)',
    } : {
      shadowColor: semantic.success,
      shadowOffset: { width: 0, height: isMobile ? 4 : 4 },
      shadowOpacity: isMobile ? 0.35 : 0.3,
      shadowRadius: isMobile ? 10 : 8,
      elevation: isMobile ? 5 : 4,
    }),
  },
  profileButtonText: {
    color: semantic.surface,
    fontSize: isMobile ? 14 : 15,
    fontWeight: '700',
    letterSpacing: isMobile ? 0.3 : 0.2,
  },
  searchResultsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Platform.OS === 'web' ? 20 : 20,
    paddingVertical: Platform.OS === 'web' ? 20 : 15,
    backgroundColor: semantic.surface,
    borderBottomWidth: 1,
    borderBottomColor: semantic.border,
  },
  searchResultsTitle: {
    fontSize: Platform.OS === 'web' ? 24 : 20,
    fontWeight: '700',
    color: semantic.textPrimary,
    flex: 1,
    textAlign: 'center',
  },
  categoryFilterHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Platform.OS === 'web' ? 20 : 24,
    paddingVertical: Platform.OS === 'web' ? 15 : 18,
    backgroundColor: semantic.surface,
    borderBottomWidth: Platform.OS === 'web' ? 1 : 3,
    borderBottomColor: Platform.OS === 'web' ? semantic.border : semantic.primary,
  },
  categoryFilterTitle: {
    fontSize: Platform.OS === 'web' ? 20 : 24,
    fontWeight: Platform.OS === 'web' ? 'bold' : '900',
    color: semantic.textPrimary,
    flex: 1,
    textAlign: 'center',
    ...(Platform.OS !== 'web' ? {
      letterSpacing: -0.3,
      textShadowColor: 'rgba(0, 0, 0, 0.1)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    } : {}),
  },
  backButton: {
    padding: 8,
  },
  backButtonText: {
    fontSize: 16,
    color: semantic.primary,
    fontWeight: '600',
  },
  placeholder: {
    width: 60,
  },
  servicesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    ...(Platform.OS === 'web' ? {
      gap: isMobileWeb ? 16 : 24,
      justifyContent: 'flex-start',
    } : {
      gap: 16,
      paddingHorizontal: 0,
      paddingBottom: 20,
      justifyContent: 'flex-start',
    }),
  },
  servicesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Platform.OS === 'web' ? 20 : 16,
    width: '100%',
    paddingHorizontal: Platform.OS === 'web' ? 0 : 16,
    gap: Platform.OS === 'web' ? 24 : 12,
  },
  serviceCardWrapper: {
    ...(Platform.OS === 'web' ? {
      width: '48%',
    } : {
      width: '100%', // Full width on mobile (1 column)
    }),
    marginBottom: Platform.OS === 'web' ? 0 : 16,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 20,
  },
  emptyStateIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: semantic.textSecondary,
    marginBottom: 8,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#95A5A6',
    textAlign: 'center',
  },
  searchResultsScroll: {
    flex: 1,
  },
  providersSection: {
    paddingHorizontal: Platform.OS === 'web' ? 32 : 20,
    paddingTop: Platform.OS === 'web' ? 32 : 24,
    paddingBottom: Platform.OS === 'web' ? 24 : 20,
    marginBottom: Platform.OS === 'web' ? 32 : 24,
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? 20 : 16,
    marginHorizontal: Platform.OS === 'web' ? 24 : 16,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 16px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.04)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    }),
  },
  sectionTitleSecondary: {
    fontSize: Platform.OS === 'web' ? 26 : 24,
    fontWeight: Platform.OS === 'web' ? '800' : '900',
    color: semantic.textPrimary,
    marginBottom: Platform.OS === 'web' ? 24 : 22,
    marginTop: Platform.OS === 'web' ? 0 : 8,
    paddingBottom: Platform.OS === 'web' ? 16 : 14,
    borderBottomWidth: Platform.OS === 'web' ? 3 : 4,
    borderBottomColor: semantic.primary,
    alignSelf: 'flex-start',
    paddingRight: Platform.OS === 'web' ? 24 : 24,
    paddingLeft: Platform.OS === 'web' ? 0 : 4,
    letterSpacing: Platform.OS === 'web' ? -0.5 : -0.4,
    ...(Platform.OS !== 'web' ? {
      textShadowColor: 'rgba(0, 0, 0, 0.1)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    } : {}),
  },
  providersContainer: {
    gap: 12,
  },
  providerCard: {
    flexDirection: 'row',
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? 16 : 14,
    padding: Platform.OS === 'web' ? 20 : 16,
    alignItems: 'center',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08), 0 1px 3px rgba(0, 0, 0, 0.05)',
      transition: 'all 0.2s ease',
      cursor: 'pointer',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    }),
  },
  providerImageContainer: {
    width: Platform.OS === 'web' ? 60 : 56,
    height: Platform.OS === 'web' ? 60 : 56,
    borderRadius: Platform.OS === 'web' ? 30 : 28,
    overflow: 'hidden',
    marginRight: 16,
  },
  providerImage: {
    width: '100%',
    height: '100%',
  },
  providerImagePlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: semantic.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  providerImagePlaceholderText: {
    fontSize: Platform.OS === 'web' ? 24 : 22,
    fontWeight: '700',
    color: semantic.surface,
  },
  providerInfo: {
    flex: 1,
  },
  providerName: {
    fontSize: Platform.OS === 'web' ? 18 : 16,
    fontWeight: '700',
    color: semantic.textPrimary,
    marginBottom: 4,
  },
  providerServicesCount: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: semantic.textSecondary,
    marginBottom: 4,
  },
  providerRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  providerRatingText: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    fontWeight: '600',
    color: semantic.warning,
  },
  providerReviewCount: {
    fontSize: Platform.OS === 'web' ? 13 : 12,
    color: semantic.textMuted,
  },
  providerArrow: {
    marginLeft: 12,
  },
  providerArrowText: {
    fontSize: Platform.OS === 'web' ? 20 : 18,
    color: semantic.textMuted,
  },
  // Filter Styles
  filterButton: {
    backgroundColor: colors.neutral[100],
    paddingHorizontal: Platform.OS === 'web' ? (isMobileWeb ? 10 : 16) : 14,
    paddingVertical: Platform.OS === 'web' ? (isMobileWeb ? 10 : 12) : 10,
    borderRadius: Platform.OS === 'web' ? (isMobileWeb ? 10 : 12) : 10,
    marginRight: Platform.OS === 'web' ? (isMobileWeb ? 6 : 8) : 6,
    position: 'relative',
    ...(Platform.OS === 'web' ? {
      transition: 'all 0.2s ease',
      cursor: 'pointer',
    } : {}),
  },
  filterButtonActive: {
    backgroundColor: semantic.primary,
  },
  filterButtonText: {
    color: colors.neutral[600],
    fontSize: Platform.OS === 'web' ? (isMobileWeb ? 12 : 14) : 13,
    fontWeight: '600',
  },
  filterButtonTextActive: {
    color: semantic.surface,
  },
  filterBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: semantic.success,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 2px 4px rgba(16, 185, 129, 0.4)',
    } : {}),
  },
  filterPanel: {
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? 16 : 14,
    marginTop: Platform.OS === 'web' ? 16 : 12,
    marginHorizontal: Platform.OS === 'web' ? 0 : 0,
    maxHeight: Platform.OS === 'web' ? 800 : 750,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.12), 0 4px 8px rgba(0, 0, 0, 0.08)',
      borderWidth: 1,
      borderColor: semantic.border,
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 8,
    }),
  },
  filterPanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Platform.OS === 'web' ? 20 : 16,
    borderBottomWidth: 1,
    borderBottomColor: semantic.border,
  },
  filterPanelTitle: {
    fontSize: Platform.OS === 'web' ? 20 : 18,
    fontWeight: '700',
    color: '#0f172a',
  },
  filterCloseButton: {
    fontSize: Platform.OS === 'web' ? 24 : 20,
    color: semantic.textSecondary,
    fontWeight: 'bold',
    padding: 4,
  },
  filterContent: {
    maxHeight: Platform.OS === 'web' ? 650 : 600,
  },
  filterContentContainer: {
    padding: Platform.OS === 'web' ? 20 : 16,
    paddingBottom: Platform.OS === 'web' ? 20 : 24,
  },
  filterSection: {
    marginBottom: Platform.OS === 'web' ? 24 : 20,
  },
  filterLabel: {
    fontSize: Platform.OS === 'web' ? 16 : 15,
    fontWeight: '600',
    color: semantic.textPrimary,
    marginBottom: Platform.OS === 'web' ? 12 : 10,
  },
  priceRangeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Platform.OS === 'web' ? 12 : 10,
  },
  priceInputContainer: {
    flex: 1,
  },
  priceLabel: {
    fontSize: Platform.OS === 'web' ? 13 : 12,
    color: semantic.textSecondary,
    marginBottom: Platform.OS === 'web' ? 6 : 5,
    fontWeight: '500',
  },
  priceInput: {
    backgroundColor: semantic.background,
    borderWidth: 1,
    borderColor: semantic.border,
    borderRadius: Platform.OS === 'web' ? 10 : 8,
    paddingHorizontal: Platform.OS === 'web' ? 14 : 12,
    paddingVertical: Platform.OS === 'web' ? 12 : 10,
    fontSize: Platform.OS === 'web' ? 15 : 14,
    color: '#0f172a',
  },
  priceSeparatorContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Platform.OS === 'web' ? 8 : 6,
  },
  priceSeparator: {
    fontSize: Platform.OS === 'web' ? 18 : 16,
    color: semantic.textSecondary,
    fontWeight: '600',
  },
  filterInput: {
    backgroundColor: semantic.background,
    borderWidth: 1,
    borderColor: semantic.border,
    borderRadius: Platform.OS === 'web' ? 10 : 8,
    paddingHorizontal: Platform.OS === 'web' ? 14 : 12,
    paddingVertical: Platform.OS === 'web' ? 12 : 10,
    fontSize: Platform.OS === 'web' ? 15 : 14,
    color: '#0f172a',
  },
  radiusContainer: {
    marginTop: Platform.OS === 'web' ? 12 : 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Platform.OS === 'web' ? 12 : 10,
  },
  radiusLabel: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: semantic.textSecondary,
    fontWeight: '500',
    flex: 1,
  },
  radiusInput: {
    backgroundColor: semantic.background,
    borderWidth: 1,
    borderColor: semantic.border,
    borderRadius: Platform.OS === 'web' ? 10 : 8,
    paddingHorizontal: Platform.OS === 'web' ? 14 : 12,
    paddingVertical: Platform.OS === 'web' ? 10 : 8,
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: '#0f172a',
    width: Platform.OS === 'web' ? 100 : 80,
  },
  categoryButtonsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Platform.OS === 'web' ? 10 : 8,
  },
  categoryFilterButton: {
    paddingHorizontal: Platform.OS === 'web' ? 16 : 14,
    paddingVertical: Platform.OS === 'web' ? 10 : 8,
    borderRadius: Platform.OS === 'web' ? 10 : 8,
    backgroundColor: semantic.background,
    borderWidth: 1,
    borderColor: semantic.border,
    ...(Platform.OS === 'web' ? {
      transition: 'all 0.2s ease',
      cursor: 'pointer',
    } : {}),
  },
  categoryFilterButtonActive: {
    backgroundColor: semantic.primary,
    borderColor: semantic.primary,
  },
  categoryFilterButtonText: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    fontWeight: '600',
    color: semantic.textSecondary,
  },
  categoryFilterButtonTextActive: {
    color: semantic.surface,
  },
  filterActions: {
    flexDirection: 'row',
    padding: Platform.OS === 'web' ? 20 : 16,
    borderTopWidth: 1,
    borderTopColor: semantic.border,
    gap: Platform.OS === 'web' ? 12 : 10,
  },
  clearFiltersButton: {
    flex: 1,
    backgroundColor: colors.neutral[100],
    paddingVertical: Platform.OS === 'web' ? 14 : 12,
    borderRadius: Platform.OS === 'web' ? 12 : 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: semantic.border,
    ...(Platform.OS === 'web' ? {
      transition: 'all 0.2s ease',
      cursor: 'pointer',
    } : {}),
  },
  clearFiltersButtonText: {
    color: semantic.textSecondary,
    fontSize: Platform.OS === 'web' ? 15 : 14,
    fontWeight: '600',
  },
  applyFiltersButton: {
    flex: 1,
    backgroundColor: semantic.primary,
    paddingVertical: Platform.OS === 'web' ? 14 : 12,
    borderRadius: Platform.OS === 'web' ? 12 : 10,
    alignItems: 'center',
    ...(Platform.OS === 'web' ? {
      boxShadow: `0 4px 12px rgba(79, 70, 229, 0.4)`,
      transition: 'all 0.2s ease',
      cursor: 'pointer',
    } : {
      shadowColor: semantic.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 4,
    }),
  },
  applyFiltersButtonText: {
    color: semantic.surface,
    fontSize: Platform.OS === 'web' ? 15 : 14,
    fontWeight: '700',
  },
  // Provider Group Styles
  providerGroup: {
    marginBottom: Platform.OS === 'web' ? 32 : 24,
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? 20 : 16,
    padding: Platform.OS === 'web' ? 24 : 20,
    marginHorizontal: Platform.OS === 'web' ? 24 : 16,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 16px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.04)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    }),
  },
  providerGroupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: Platform.OS === 'web' ? 16 : 12,
    marginBottom: Platform.OS === 'web' ? 20 : 16,
    borderBottomWidth: 2,
    borderBottomColor: semantic.border,
    ...(Platform.OS === 'web' ? {
      cursor: 'pointer',
      transition: 'all 0.2s ease',
    } : {}),
  },
  providerGroupHeaderContent: {
    flex: 1,
  },
  providerGroupTitle: {
    fontSize: Platform.OS === 'web' ? 22 : 20,
    fontWeight: '800',
    color: semantic.textPrimary,
    marginBottom: Platform.OS === 'web' ? 4 : 2,
  },
  providerGroupCount: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: semantic.textSecondary,
    fontWeight: '500',
  },
  providerGroupArrow: {
    fontSize: Platform.OS === 'web' ? 20 : 18,
    color: semantic.primary,
    fontWeight: '700',
    marginLeft: Platform.OS === 'web' ? 16 : 12,
  },
  // Category Tag Styles
  categoryTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary[100],
    paddingHorizontal: Platform.OS === 'web' ? 10 : 8,
    paddingVertical: Platform.OS === 'web' ? 4 : 3,
    borderRadius: Platform.OS === 'web' ? 12 : 10,
    gap: Platform.OS === 'web' ? 4 : 3,
    flexShrink: 0,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 1,
    }),
  },
  categoryTagIcon: {
    fontSize: Platform.OS === 'web' ? 12 : 11,
  },
  categoryTagText: {
    fontSize: Platform.OS === 'web' ? 11 : 10,
    fontWeight: '600',
    color: semantic.primary,
    textTransform: 'capitalize',
  },
  bannerCategoryTag: {
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  bannerCategoryTagText: {
    color: semantic.surface,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  ratingDropdownButton: {
    backgroundColor: semantic.background,
    borderWidth: 1,
    borderColor: semantic.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ratingDropdownText: {
    fontSize: 14,
    color: '#0f172a',
    flex: 1,
  },
  ratingDropdownPlaceholder: {
    color: semantic.textMuted,
  },
  ratingDropdownArrow: {
    fontSize: 12,
    color: semantic.textSecondary,
    marginLeft: 8,
  },
  ratingModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ratingModalContent: {
    backgroundColor: semantic.surface,
    borderRadius: 16,
    width: '85%',
    maxWidth: 400,
    maxHeight: '70%',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 10px 40px rgba(0, 0, 0, 0.15)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
    }),
  },
  ratingModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: semantic.border,
  },
  ratingModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#0f172a',
  },
  ratingModalCloseButton: {
    padding: 4,
  },
  ratingModalCloseText: {
    fontSize: 20,
    color: semantic.textSecondary,
    fontWeight: 'bold',
  },
  ratingModalBody: {
    maxHeight: 400,
  },
  ratingModalItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.neutral[100],
  },
  ratingModalItemSelected: {
    backgroundColor: '#f0f4ff',
  },
  ratingModalItemText: {
    fontSize: 15,
    color: '#0f172a',
  },
  ratingModalItemTextSelected: {
    color: semantic.primary,
    fontWeight: '600',
  },
  ratingModalCheckmark: {
    fontSize: 18,
    color: semantic.primary,
    fontWeight: 'bold',
  },
});
