import { StyleSheet, Platform } from 'react-native';

export const createStyles = (isMobile: boolean, screenWidth: number) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#F8FAFC',
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: isMobile ? 16 : 24,
      paddingVertical: 12,
      gap: 6,
    },
    backText: {
      fontSize: 15,
      color: '#2563EB',
      fontWeight: '500',
    },
    tabBar: {
      flexDirection: 'row',
      backgroundColor: '#FFFFFF',
      borderBottomWidth: 1,
      borderBottomColor: '#E2E8F0',
      paddingHorizontal: isMobile ? 8 : 16,
    },
    tab: {
      paddingHorizontal: isMobile ? 12 : 20,
      paddingVertical: 14,
      borderBottomWidth: 3,
      borderBottomColor: 'transparent',
    },
    tabActive: {
      borderBottomColor: '#2563EB',
    },
    tabText: {
      fontSize: isMobile ? 13 : 15,
      fontWeight: '600',
      color: '#64748B',
    },
    tabTextActive: {
      color: '#2563EB',
    },
    content: {
      flex: 1,
    },
    scrollContent: {
      padding: isMobile ? 16 : 24,
      paddingBottom: 40,
      ...(Platform.OS === 'web' && !isMobile
        ? { maxWidth: 900, width: '100%', alignSelf: 'center' as const }
        : {}),
    },
    card: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: isMobile ? 16 : 20,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.03,
      shadowRadius: 3,
      elevation: 1,
      ...(Platform.OS === 'web' ? { boxShadow: '0px 1px 3px rgba(0, 0, 0, 0.04)' } : {}),
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: '#0F172A',
      marginBottom: 12,
    },
    eventName: {
      fontSize: isMobile ? 22 : 26,
      fontWeight: '700',
      color: '#0F172A',
      marginBottom: 8,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
      gap: 10,
    },
    infoText: {
      fontSize: 15,
      color: '#0F172A',
    },
    infoLabel: {
      fontSize: 13,
      color: '#64748B',
    },
    description: {
      fontSize: 14,
      color: '#64748B',
      lineHeight: 22,
      marginTop: 8,
    },
    statusBadge: {
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 8,
      alignSelf: 'flex-start',
      marginBottom: 12,
    },
    statusBadgeText: {
      fontSize: 13,
      fontWeight: '600',
      textTransform: 'capitalize',
    },
    statsRow: {
      flexDirection: isMobile ? 'column' : 'row',
      gap: 12,
      marginTop: 8,
    },
    statCard: {
      flex: 1,
      backgroundColor: '#EFF6FF',
      borderRadius: 12,
      padding: 16,
      alignItems: 'center',
    },
    statValue: {
      fontSize: 20,
      fontWeight: '700',
      color: '#2563EB',
    },
    statLabel: {
      fontSize: 12,
      color: '#64748B',
      marginTop: 4,
    },
    editButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#0F172A',
      borderRadius: 10,
      paddingVertical: 12,
      gap: 8,
      marginTop: 16,
    },
    editButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '600',
    },
    // Vendors tab
    vendorCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    vendorInfo: {
      flex: 1,
    },
    vendorName: {
      fontSize: 16,
      fontWeight: '600',
      color: '#0F172A',
    },
    vendorCategory: {
      fontSize: 13,
      color: '#64748B',
      marginTop: 2,
    },
    vendorCost: {
      fontSize: 15,
      fontWeight: '600',
      color: '#2563EB',
      marginTop: 4,
    },
    unlinkButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: '#FEE2E2',
    },
    linkButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: '#2563EB',
      borderStyle: 'dashed',
      borderRadius: 12,
      paddingVertical: 16,
      gap: 8,
      marginBottom: 12,
    },
    linkButtonText: {
      fontSize: 15,
      fontWeight: '600',
      color: '#2563EB',
    },
    // Timeline tab
    timelineEntry: {
      flexDirection: 'row',
      marginBottom: 16,
      gap: 12,
    },
    timelineTime: {
      width: isMobile ? 70 : 90,
      alignItems: 'flex-end',
    },
    timelineTimeText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#2563EB',
    },
    timelineEndText: {
      fontSize: 12,
      color: '#64748B',
    },
    timelineDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: '#2563EB',
      marginTop: 4,
    },
    timelineLine: {
      width: 2,
      flex: 1,
      backgroundColor: '#BFDBFE',
      alignSelf: 'center',
      marginTop: 4,
    },
    timelineContent: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      borderRadius: 10,
      padding: 12,
      borderWidth: 1,
      borderColor: '#E2E8F0',
    },
    timelineTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: '#0F172A',
    },
    timelineDesc: {
      fontSize: 13,
      color: '#64748B',
      marginTop: 4,
    },
    timelineActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: 8,
      gap: 8,
    },
    // Checklist tab
    progressBar: {
      height: 8,
      backgroundColor: '#E2E8F0',
      borderRadius: 4,
      overflow: 'hidden',
      marginBottom: 16,
    },
    progressFill: {
      height: '100%',
      backgroundColor: '#22C55E',
      borderRadius: 4,
    },
    progressText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#0F172A',
      marginBottom: 8,
    },
    checklistItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#F1F5F9',
      gap: 12,
    },
    checkbox: {
      width: 24,
      height: 24,
      borderRadius: 6,
      borderWidth: 2,
      borderColor: '#CBD5E1',
      justifyContent: 'center',
      alignItems: 'center',
    },
    checkboxChecked: {
      backgroundColor: '#22C55E',
      borderColor: '#22C55E',
    },
    checklistTitle: {
      flex: 1,
      fontSize: 15,
      color: '#0F172A',
    },
    checklistTitleCompleted: {
      textDecorationLine: 'line-through',
      color: '#64748B',
    },
    dueDateBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      backgroundColor: '#F1F5F9',
    },
    dueDateOverdue: {
      backgroundColor: '#FEE2E2',
    },
    dueDateText: {
      fontSize: 11,
      fontWeight: '500',
      color: '#64748B',
    },
    dueDateOverdueText: {
      color: '#DC2626',
    },
    categoryTag: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      backgroundColor: '#EFF6FF',
    },
    categoryTagText: {
      fontSize: 11,
      fontWeight: '500',
      color: '#2563EB',
    },
    addItemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 12,
      gap: 8,
    },
    addItemInput: {
      flex: 1,
      backgroundColor: '#F8FAFC',
      borderWidth: 1,
      borderColor: '#E2E8F0',
      borderRadius: 8,
      padding: 10,
      fontSize: 14,
      color: '#0F172A',
    },
    addItemButton: {
      backgroundColor: '#0F172A',
      borderRadius: 8,
      padding: 10,
    },
    // Budget tab
    budgetSummaryCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: isMobile ? 16 : 24,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.03,
      shadowRadius: 3,
      elevation: 1,
      ...(Platform.OS === 'web' ? { boxShadow: '0px 1px 3px rgba(0, 0, 0, 0.04)' } : {}),
    },
    budgetRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    budgetLabel: {
      fontSize: 15,
      color: '#64748B',
    },
    budgetValue: {
      fontSize: 16,
      fontWeight: '700',
      color: '#0F172A',
    },
    budgetRemaining: {
      fontSize: 16,
      fontWeight: '700',
    },
    budgetProgressBar: {
      height: 12,
      backgroundColor: '#E2E8F0',
      borderRadius: 6,
      overflow: 'hidden',
      marginVertical: 12,
    },
    budgetProgressFill: {
      height: '100%',
      borderRadius: 6,
    },
    categoryRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: '#F1F5F9',
    },
    categoryName: {
      fontSize: 14,
      fontWeight: '500',
      color: '#0F172A',
      textTransform: 'capitalize',
      flex: 1,
    },
    categoryAmount: {
      fontSize: 14,
      fontWeight: '600',
      color: '#0F172A',
    },
    categoryBar: {
      height: 4,
      backgroundColor: '#E2E8F0',
      borderRadius: 2,
      flex: 1,
      marginHorizontal: 12,
      overflow: 'hidden',
    },
    categoryBarFill: {
      height: '100%',
      backgroundColor: '#2563EB',
      borderRadius: 2,
    },
    // Shared action buttons
    iconButton: {
      padding: 6,
      borderRadius: 6,
    },
    // Link modal
    linkModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 16,
    },
    linkModalContainer: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      width: isMobile ? '100%' : Math.min(500, screenWidth - 48),
      maxHeight: '70%',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
      ...(Platform.OS === 'web' ? { boxShadow: '0px 4px 12px rgba(0, 0, 0, 0.12)' } : {}),
    },
    linkModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      borderBottomWidth: 1,
      borderBottomColor: '#E2E8F0',
    },
    linkModalTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: '#0F172A',
    },
    linkModalItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#F1F5F9',
    },
    linkModalItemName: {
      fontSize: 15,
      fontWeight: '500',
      color: '#0F172A',
    },
    linkModalItemDate: {
      fontSize: 13,
      color: '#64748B',
    },
    linkModalEmpty: {
      padding: 32,
      alignItems: 'center',
    },
    linkModalEmptyText: {
      fontSize: 14,
      color: '#64748B',
      marginTop: 8,
    },
    // Timeline form
    formRow: {
      flexDirection: isMobile ? 'column' : 'row',
      gap: isMobile ? 0 : 12,
      marginBottom: 8,
    },
    formField: {
      flex: 1,
    },
    formLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: '#0F172A',
      marginBottom: 4,
      marginTop: 8,
    },
    formInput: {
      backgroundColor: '#F8FAFC',
      borderWidth: 1,
      borderColor: '#E2E8F0',
      borderRadius: 8,
      padding: 10,
      fontSize: 14,
      color: '#0F172A',
    },
    formButton: {
      backgroundColor: '#0F172A',
      borderRadius: 10,
      paddingVertical: 12,
      alignItems: 'center',
      marginTop: 12,
    },
    formButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '600',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 40,
    },
  });
