import { StyleSheet, Platform, Dimensions } from 'react-native';
import { colors, semantic } from '../../theme';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');
const isMobile = screenWidth < 768;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: semantic.background,
  },
  scrollView: {
    flex: 1,
  },
  contentWrapper: {
    flex: 1,
    ...(Platform.OS === 'web' ? {
      alignItems: 'center',
      paddingVertical: 20,
    } : {}),
  },
  content: {
    ...(Platform.OS === 'web' ? {
      width: '100%',
      maxWidth: 800,
      backgroundColor: semantic.surface,
      borderRadius: 20,
      padding: 24,
      marginHorizontal: 'auto',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    } : {
      width: '100%',
    }),
  },
  modernProfileSection: {
    backgroundColor: Platform.OS === 'web' ? 'transparent' : semantic.surface,
    margin: Platform.OS === 'web' ? 0 : isMobile ? 12 : 20,
    marginBottom: Platform.OS === 'web' ? 24 : isMobile ? 12 : 20,
    borderRadius: Platform.OS === 'web' ? 0 : 20,
    padding: Platform.OS === 'web' ? 0 : isMobile ? 20 : 24,
    flexDirection: Platform.OS === 'web' ? 'row' : isMobile ? 'column' : 'row',
    alignItems: 'center',
    ...(Platform.OS === 'web' ? {} : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    }),
  },
  modernAvatarContainer: {
    position: 'relative',
    marginRight: Platform.OS === 'web' ? 24 : isMobile ? 0 : 20,
    marginBottom: Platform.OS === 'web' ? 0 : isMobile ? 16 : 0,
  },
  modernAvatarPlaceholder: {
    width: Platform.OS === 'web' ? 100 : isMobile ? 80 : 90,
    height: Platform.OS === 'web' ? 100 : isMobile ? 80 : 90,
    borderRadius: Platform.OS === 'web' ? 50 : isMobile ? 40 : 45,
    backgroundColor: semantic.primary,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  modernAvatarText: {
    fontSize: Platform.OS === 'web' ? 40 : 32,
    fontWeight: '700',
    color: semantic.surface,
  },
  modernAvatarImage: {
    width: Platform.OS === 'web' ? 100 : isMobile ? 80 : 90,
    height: Platform.OS === 'web' ? 100 : isMobile ? 80 : 90,
    borderRadius: Platform.OS === 'web' ? 50 : isMobile ? 40 : 45,
  },
  modernVerifiedBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: Platform.OS === 'web' ? 32 : 28,
    height: Platform.OS === 'web' ? 32 : 28,
    borderRadius: Platform.OS === 'web' ? 16 : 14,
    backgroundColor: semantic.success,
    borderWidth: 3,
    borderColor: semantic.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modernVerifiedIcon: {
    fontSize: Platform.OS === 'web' ? 16 : 14,
    color: semantic.surface,
    fontWeight: 'bold',
  },
  modernUserInfo: {
    flex: 1,
    alignItems: Platform.OS === 'web' ? 'flex-start' : isMobile ? 'center' : 'flex-start',
  },
  modernUserName: {
    fontSize: Platform.OS === 'web' ? 28 : isMobile ? 22 : 24,
    fontWeight: '700',
    color: semantic.textPrimary,
    marginBottom: Platform.OS === 'web' ? 8 : 6,
    letterSpacing: Platform.OS === 'web' ? -0.5 : 0,
  },
  modernUserEmailContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modernUserEmailIcon: {
    fontSize: Platform.OS === 'web' ? 16 : 14,
    marginRight: 6,
  },
  modernUserEmail: {
    fontSize: Platform.OS === 'web' ? 16 : isMobile ? 14 : 15,
    color: semantic.textSecondary,
    fontWeight: '500',
  },
  profileSection: {
    backgroundColor: semantic.surface,
    margin: isMobile ? 12 : 20,
    borderRadius: 16,
    padding: isMobile ? 16 : 24,
    flexDirection: isMobile ? 'column' : 'row',
    alignItems: isMobile ? 'center' : 'center',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
    } : {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    }),
  },
  avatarContainer: {
    width: isMobile ? 70 : 80,
    height: isMobile ? 70 : 80,
    borderRadius: isMobile ? 35 : 40,
    backgroundColor: semantic.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: isMobile ? 0 : 20,
    marginBottom: isMobile ? 12 : 0,
    overflow: 'hidden',
  },
  avatarText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: semantic.surface,
  },
  avatarImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: isMobile ? 20 : 24,
    fontWeight: 'bold',
    color: semantic.textPrimary,
    marginBottom: 4,
    textAlign: isMobile ? 'center' : 'left',
  },
  userEmail: {
    fontSize: isMobile ? 14 : 16,
    color: semantic.textSecondary,
    marginBottom: 8,
    textAlign: isMobile ? 'center' : 'left',
  },
  verifiedBadge: {
    backgroundColor: '#E8F5E8',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  verifiedText: {
    fontSize: 12,
    color: '#34C759',
    fontWeight: '600',
  },
  modernSection: {
    marginHorizontal: Platform.OS === 'web' ? 0 : isMobile ? 16 : 24,
    marginBottom: Platform.OS === 'web' ? 32 : isMobile ? 24 : 32,
    marginTop: Platform.OS === 'web' ? 24 : isMobile ? 16 : 24,
  },
  modernSectionTitle: {
    fontSize: Platform.OS === 'web' ? 24 : isMobile ? 20 : 22,
    fontWeight: '800',
    color: semantic.textPrimary,
    marginBottom: Platform.OS === 'web' ? 20 : 16,
    paddingBottom: Platform.OS === 'web' ? 12 : 10,
    borderBottomWidth: 3,
    borderBottomColor: semantic.primary,
    alignSelf: 'flex-start',
    paddingRight: Platform.OS === 'web' ? 24 : 20,
    marginLeft: Platform.OS === 'web' ? 0 : 0,
    letterSpacing: Platform.OS === 'web' ? -0.4 : -0.2,
  },
  modernSectionCard: {
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? 20 : 16,
    padding: Platform.OS === 'web' ? 4 : 8,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    }),
  },
  section: {
    marginHorizontal: isMobile ? 16 : 24,
    marginBottom: isMobile ? 24 : 32,
    marginTop: isMobile ? 16 : 24,
    paddingHorizontal: isMobile ? 20 : 24,
    paddingVertical: isMobile ? 20 : 24,
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? 20 : 16,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 16px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.04)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    }),
  },
  sectionTitle: {
    fontSize: isMobile ? 20 : 24,
    fontWeight: '800',
    color: semantic.textPrimary,
    marginBottom: Platform.OS === 'web' ? 20 : 16,
    paddingBottom: Platform.OS === 'web' ? 12 : 10,
    borderBottomWidth: 3,
    borderBottomColor: semantic.primary,
    alignSelf: 'flex-start',
    paddingRight: Platform.OS === 'web' ? 24 : 20,
    letterSpacing: Platform.OS === 'web' ? -0.3 : -0.2,
  },
  modernApplyProviderButton: {
    backgroundColor: semantic.primary,
    borderRadius: Platform.OS === 'web' ? 16 : 14,
    padding: Platform.OS === 'web' ? 20 : 16,
    marginTop: Platform.OS === 'web' ? 8 : 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 12px rgba(99, 102, 241, 0.3)',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
      ':hover': {
        backgroundColor: '#4F46E5',
        boxShadow: '0 6px 16px rgba(99, 102, 241, 0.4)',
        transform: 'translateY(-1px)',
      },
    } : {
      shadowColor: semantic.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    }),
  },
  modernApplyProviderIconContainer: {
    width: Platform.OS === 'web' ? 48 : 44,
    height: Platform.OS === 'web' ? 48 : 44,
    borderRadius: Platform.OS === 'web' ? 24 : 22,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Platform.OS === 'web' ? 16 : 14,
  },
  modernApplyProviderIcon: {
    fontSize: Platform.OS === 'web' ? 24 : 22,
  },
  modernApplyProviderTextContainer: {
    flex: 1,
  },
  modernApplyProviderTitle: {
    fontSize: Platform.OS === 'web' ? 18 : isMobile ? 15 : 16,
    fontWeight: '600',
    color: semantic.surface,
    marginBottom: Platform.OS === 'web' ? 4 : 2,
  },
  modernApplyProviderSubtitle: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  applyProviderButton: {
    backgroundColor: semantic.primary,
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 2px 8px rgba(108, 99, 255, 0.3)',
    } : {
      shadowColor: semantic.primary,
    shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 3,
    }),
  },
  applyProviderIcon: {
    fontSize: 24,
    marginRight: 16,
  },
  applyProviderTextContainer: {
    flex: 1,
  },
  applyProviderTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: semantic.surface,
    marginBottom: 2,
  },
  applyProviderSubtitle: {
    fontSize: 14,
    color: '#E0E0FF',
  },
  modernMenuButton: {
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? 16 : 14,
    padding: Platform.OS === 'web' ? 18 : isMobile ? 14 : 16,
    marginBottom: Platform.OS === 'web' ? 4 : 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...(Platform.OS === 'web' ? {
      cursor: 'pointer',
      transition: 'all 0.2s ease',
    } : {}),
  },
  modernMenuButtonLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  modernMenuIconContainer: {
    width: Platform.OS === 'web' ? 48 : 44,
    height: Platform.OS === 'web' ? 48 : 44,
    borderRadius: Platform.OS === 'web' ? 24 : 22,
    backgroundColor: colors.primary[50],
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Platform.OS === 'web' ? 16 : 14,
  },
  modernMenuIcon: {
    fontSize: Platform.OS === 'web' ? 22 : 20,
  },
  modernMenuTextContainer: {
    flex: 1,
  },
  modernMenuTitle: {
    fontSize: Platform.OS === 'web' ? 17 : isMobile ? 15 : 16,
    fontWeight: '600',
    color: semantic.textPrimary,
    marginBottom: Platform.OS === 'web' ? 4 : 2,
  },
  modernMenuSubtitle: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: semantic.textSecondary,
    lineHeight: Platform.OS === 'web' ? 20 : 18,
  },
  modernMenuButtonRight: {
    marginLeft: 12,
  },
  modernArrowIcon: {
    fontSize: Platform.OS === 'web' ? 24 : 20,
    color: colors.neutral[300],
    fontWeight: 'bold',
  },
  menuButton: {
    backgroundColor: semantic.surface,
    borderRadius: 12,
    padding: isMobile ? 12 : 16,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 1px 4px rgba(0, 0, 0, 0.05)',
    } : {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    }),
  },
  menuButtonLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  menuIcon: {
    fontSize: 24,
    marginRight: 16,
    width: 30,
    textAlign: 'center',
  },
  menuTextContainer: {
    flex: 1,
  },
  menuTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: semantic.textPrimary,
    marginBottom: 2,
  },
  menuSubtitle: {
    fontSize: 14,
    color: semantic.textSecondary,
  },
  menuButtonRight: {
    marginLeft: 12,
  },
  arrowIcon: {
    fontSize: 20,
    color: '#A4B0BE',
    fontWeight: 'bold',
  },
  modernLogoutButton: {
    backgroundColor: semantic.error,
    borderRadius: Platform.OS === 'web' ? 16 : 14,
    padding: Platform.OS === 'web' ? 18 : 16,
    alignItems: 'center',
    marginTop: Platform.OS === 'web' ? 0 : 20,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 12px rgba(239, 68, 68, 0.3)',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
      ':hover': {
        backgroundColor: colors.error[600],
        boxShadow: '0 6px 16px rgba(239, 68, 68, 0.4)',
      },
    } : {
      shadowColor: semantic.error,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    }),
  },
  modernLogoutButtonText: {
    color: semantic.surface,
    fontSize: Platform.OS === 'web' ? 17 : 16,
    fontWeight: '600',
    letterSpacing: Platform.OS === 'web' ? 0.3 : 0,
  },
  logoutButton: {
    backgroundColor: semantic.error,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginTop: 20,
  },
  logoutButtonText: {
    color: semantic.surface,
    fontSize: 16,
    fontWeight: '600',
  },
  bottomSpacing: {
    height: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Math.max(10, screenWidth * 0.05),
  },
  modalContent: {
    backgroundColor: semantic.surface,
    borderRadius: 16,
    width: '100%',
    maxWidth: Math.min(500, screenWidth * 0.95),
    maxHeight: '90%',
    marginHorizontal: 10,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 10,
    }),
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: semantic.border,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: semantic.textPrimary,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: semantic.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 18,
    color: semantic.textSecondary,
    fontWeight: 'bold',
  },
  modalBody: {
    padding: 20,
    maxHeight: screenHeight * 0.6,
  },
  documentSection: {
    marginBottom: 24,
  },
  documentSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: semantic.textPrimary,
    marginBottom: 12,
  },
  modalDescription: {
    fontSize: 14,
    color: semantic.textSecondary,
    lineHeight: 20,
    marginBottom: 12,
  },
  modalNote: {
    fontSize: 12,
    color: semantic.primary,
    fontWeight: '600',
    marginBottom: 20,
  },
  documentPreviewContainer: {
    marginBottom: 12,
    alignItems: 'center',
  },
  documentPreview: {
    width: '100%',
    height: 200,
    borderRadius: 12,
    backgroundColor: semantic.background,
    borderWidth: 1,
    borderColor: semantic.border,
    marginBottom: 12,
  },
  removeDocumentButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: semantic.error,
  },
  removeDocumentText: {
    color: semantic.surface,
    fontSize: 14,
    fontWeight: '600',
  },
  uploadButton: {
    backgroundColor: semantic.primary,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginBottom: 20,
  },
  uploadButtonDisabled: {
    opacity: 0.6,
  },
  uploadButtonText: {
    color: semantic.surface,
    fontSize: 16,
    fontWeight: '600',
  },
  modalFooter: {
    flexDirection: 'row',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: semantic.border,
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: semantic.background,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  cancelButtonText: {
    color: semantic.textSecondary,
    fontSize: 16,
    fontWeight: '600',
  },
  submitButton: {
    flex: 1,
    backgroundColor: semantic.primary,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: semantic.surface,
    fontSize: 16,
    fontWeight: '600',
  },
  modernRejectionNotice: {
    backgroundColor: '#FFFBEB',
    borderWidth: 1,
    borderColor: '#FDE68A',
    borderRadius: Platform.OS === 'web' ? 16 : 14,
    padding: Platform.OS === 'web' ? 18 : 16,
    marginTop: Platform.OS === 'web' ? 8 : 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...(Platform.OS === 'web' ? {
      cursor: 'pointer',
      transition: 'all 0.2s ease',
      boxShadow: '0 1px 3px rgba(245, 158, 11, 0.1)',
      ':hover': {
        backgroundColor: colors.warning[50],
        borderColor: '#FCD34D',
      },
    } : {}),
  },
  modernRejectionIconContainer: {
    width: Platform.OS === 'web' ? 44 : 40,
    height: Platform.OS === 'web' ? 44 : 40,
    borderRadius: Platform.OS === 'web' ? 22 : 20,
    backgroundColor: colors.warning[50],
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Platform.OS === 'web' ? 16 : 14,
  },
  modernRejectionIcon: {
    fontSize: Platform.OS === 'web' ? 22 : 20,
  },
  modernRejectionTextContainer: {
    flex: 1,
  },
  modernRejectionTitle: {
    fontSize: Platform.OS === 'web' ? 17 : isMobile ? 15 : 16,
    fontWeight: '600',
    color: '#92400E',
    marginBottom: Platform.OS === 'web' ? 4 : 2,
  },
  modernRejectionSubtitle: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: '#B45309',
    lineHeight: Platform.OS === 'web' ? 20 : 18,
  },
  rejectionNotice: {
    backgroundColor: '#FFF3CD',
    borderWidth: 1,
    borderColor: '#FFC107',
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rejectionIcon: {
    fontSize: 24,
    marginRight: 16,
  },
  rejectionTextContainer: {
    flex: 1,
  },
  rejectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#856404',
    marginBottom: 2,
  },
  rejectionSubtitle: {
    fontSize: 14,
    color: '#856404',
    opacity: 0.8,
  },
  rejectionModalContent: {
    backgroundColor: semantic.surface,
    borderRadius: 16,
    width: '100%',
    maxWidth: 500,
    maxHeight: '90%',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 10,
    }),
  },
  rejectionModalBody: {
    padding: 20,
  },
  rejectionModalDescription: {
    fontSize: 14,
    color: semantic.textSecondary,
    lineHeight: 20,
    marginBottom: 20,
  },
  rejectionReasonBox: {
    backgroundColor: '#FFF3CD',
    borderWidth: 1,
    borderColor: '#FFC107',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  rejectionReasonLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#856404',
    marginBottom: 8,
  },
  rejectionReasonText: {
    fontSize: 14,
    color: '#856404',
    lineHeight: 20,
  },
  rejectionModalNote: {
    fontSize: 12,
    color: semantic.textSecondary,
    fontStyle: 'italic',
    textAlign: 'center',
  },
  closeModalButton: {
    flex: 1,
    backgroundColor: semantic.background,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginRight: 12,
  },
  closeModalButtonText: {
    color: semantic.textSecondary,
    fontSize: 16,
    fontWeight: '600',
  },
  reapplyButton: {
    flex: 1,
    backgroundColor: semantic.primary,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 12px rgba(108, 99, 255, 0.4)',
    } : {
      shadowColor: semantic.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    }),
  },
  reapplyButtonIcon: {
    fontSize: 18,
    marginRight: 8,
  },
  reapplyButtonText: {
    color: semantic.surface,
    fontSize: 16,
    fontWeight: '700',
  },
  modernPendingNotice: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: Platform.OS === 'web' ? 16 : 14,
    padding: Platform.OS === 'web' ? 18 : 16,
    marginTop: Platform.OS === 'web' ? 8 : 8,
    flexDirection: 'row',
    alignItems: 'center',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 1px 3px rgba(59, 130, 246, 0.1)',
    } : {}),
  },
  modernPendingIconContainer: {
    width: Platform.OS === 'web' ? 44 : 40,
    height: Platform.OS === 'web' ? 44 : 40,
    borderRadius: Platform.OS === 'web' ? 22 : 20,
    backgroundColor: '#DBEAFE',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Platform.OS === 'web' ? 16 : 14,
  },
  modernPendingIcon: {
    fontSize: Platform.OS === 'web' ? 22 : 20,
  },
  modernPendingTextContainer: {
    flex: 1,
  },
  modernPendingTitle: {
    fontSize: Platform.OS === 'web' ? 17 : isMobile ? 15 : 16,
    fontWeight: '600',
    color: '#1E40AF',
    marginBottom: Platform.OS === 'web' ? 4 : 2,
  },
  modernPendingSubtitle: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: '#3B82F6',
    lineHeight: Platform.OS === 'web' ? 20 : 18,
  },
  pendingNotice: {
    backgroundColor: '#E3F2FD',
    borderWidth: 1,
    borderColor: '#2196F3',
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  pendingIcon: {
    fontSize: 24,
    marginRight: 16,
  },
  pendingTextContainer: {
    flex: 1,
  },
  pendingTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1976D2',
    marginBottom: 2,
  },
  pendingSubtitle: {
    fontSize: 14,
    color: '#1976D2',
    opacity: 0.8,
  },
});
