import { StyleSheet, Platform, Dimensions } from 'react-native';
import { colors, semantic } from '../../theme';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');
const isMobile = screenWidth < 768;

export const styles = StyleSheet.create({
  container: {
    paddingTop: Platform.OS === 'web' ? (screenWidth < 768 ? 0 : 20) : 10,
    paddingBottom: Platform.OS === 'web' ? (screenWidth < 768 ? 0 : 20) : 10,
    flex: 1,
    backgroundColor: Platform.OS === 'web' ? '#F0F2F5' : semantic.background,
    position: 'relative',
    ...(Platform.OS === 'web' ? {
      justifyContent: screenWidth < 768 ? 'flex-start' : 'center',
      alignItems: 'center',
    } : {}),
  },
  // Background Decorative Elements
  backgroundContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0,
    overflow: 'hidden',
  },
  backgroundGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: semantic.background,
  },
  backgroundGradientWeb: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    ...(Platform.OS === 'web' ? {
      backgroundImage: 'linear-gradient(135deg, #F0F2F5 0%, #E8F0FE 100%)',
    } : {}),
  },
  webCardContainer: {
    width: screenWidth < 768 ? '100%' : '90%',
    maxWidth: screenWidth < 768 ? '100%' : 900,
    maxHeight: screenWidth < 768 ? '100%' : (screenHeight * 0.95),
    backgroundColor: semantic.surface,
    borderRadius: screenWidth < 768 ? 0 : 16,
    overflow: 'hidden',
    ...(Platform.OS === 'web' ? {
      boxShadow: screenWidth < 768 ? 'none' : '0 20px 60px rgba(0, 0, 0, 0.15), 0 8px 24px rgba(0, 0, 0, 0.1)',
    } : {}),
  },
  backgroundCircle1: {
    position: 'absolute',
    width: Platform.OS === 'web' ? 500 : 350,
    height: Platform.OS === 'web' ? 500 : 350,
    borderRadius: Platform.OS === 'web' ? 250 : 175,
    backgroundColor: 'rgba(79, 70, 229, 0.06)',
    top: Platform.OS === 'web' ? -150 : -100,
    right: Platform.OS === 'web' ? -150 : -100,
    ...(Platform.OS === 'web' ? {
      filter: 'blur(70px)',
    } : {}),
  },
  backgroundCircle2: {
    position: 'absolute',
    width: Platform.OS === 'web' ? 400 : 300,
    height: Platform.OS === 'web' ? 400 : 300,
    borderRadius: Platform.OS === 'web' ? 200 : 150,
    backgroundColor: 'rgba(139, 92, 246, 0.05)',
    bottom: Platform.OS === 'web' ? -100 : -80,
    left: Platform.OS === 'web' ? -100 : -80,
    ...(Platform.OS === 'web' ? {
      filter: 'blur(60px)',
    } : {}),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: semantic.background,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: semantic.textSecondary,
    fontWeight: '500',
  },
  content: {
    flex: 1,
    zIndex: 1,
    maxHeight: Platform.OS === 'web' ? (screenWidth < 768 ? undefined : (screenHeight * 0.95 - 200)) : undefined,
  },
  contentContainer: {
    paddingBottom: Platform.OS === 'web' ? (screenWidth < 768 ? 100 : 24) : (isMobile ? 100 : 40),
    backgroundColor: 'transparent',
  },
  // Modern Hero Image Section
  heroImageContainer: {
    width: '100%',
    height: Platform.OS === 'web' ? (screenWidth < 768 ? 300 : 400) : 350,
    backgroundColor: semantic.textPrimary,
    position: 'relative',
    overflow: 'hidden',
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroImagePlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: semantic.textPrimary,
  },
  heroImagePlaceholderIcon: {
    fontSize: Platform.OS === 'web' ? 120 : 100,
    opacity: 0.3,
  },
  ratingBadgeOverlay: {
    position: 'absolute',
    top: Platform.OS === 'web' ? 20 : 16,
    right: Platform.OS === 'web' ? 20 : 16,
    backgroundColor: semantic.success,
    borderRadius: 24,
    paddingHorizontal: Platform.OS === 'web' ? 16 : 14,
    paddingVertical: Platform.OS === 'web' ? 10 : 8,
    flexDirection: 'row',
    alignItems: 'center',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 12px rgba(16, 185, 129, 0.4)',
    } : {
      shadowColor: semantic.success,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 6,
    }),
  },
  ratingBadgeIcon: {
    fontSize: Platform.OS === 'web' ? 18 : 16,
    marginRight: 6,
  },
  ratingBadgeText: {
    color: semantic.surface,
    fontSize: Platform.OS === 'web' ? 14 : 13,
    fontWeight: '700',
  },
  // Modern Info Card
  infoCard: {
    marginTop: Platform.OS === 'web' ? (screenWidth < 768 ? -30 : -40) : -30,
    marginHorizontal: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 32) : 20,
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 20) : 20,
    padding: Platform.OS === 'web' ? (screenWidth < 768 ? 20 : 28) : 24,
    position: 'relative',
    zIndex: 2,
    ...(Platform.OS === 'web' ? {
      boxShadow: screenWidth < 768 ? '0 4px 16px rgba(0, 0, 0, 0.08)' : '0 10px 40px rgba(0, 0, 0, 0.1), 0 4px 12px rgba(0, 0, 0, 0.06)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 20,
      elevation: 8,
    }),
  },
  serviceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: Platform.OS === 'web' ? 24 : 20,
  },
  serviceHeaderLeft: {
    flex: 1,
  },
  serviceName: {
    fontSize: Platform.OS === 'web' ? (screenWidth < 768 ? 24 : 32) : 28,
    fontWeight: '800',
    color: colors.neutral[900],
    marginBottom: Platform.OS === 'web' ? (screenWidth < 768 ? 10 : 12) : 10,
    letterSpacing: -0.5,
    lineHeight: Platform.OS === 'web' ? (screenWidth < 768 ? 30 : 40) : 36,
  },
  serviceMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  providerBadge: {
    backgroundColor: semantic.background,
    borderRadius: 20,
    paddingHorizontal: Platform.OS === 'web' ? 14 : 12,
    paddingVertical: Platform.OS === 'web' ? 6 : 5,
    borderWidth: 1,
    borderColor: semantic.border,
  },
  providerBadgeText: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: colors.neutral[600],
    fontWeight: '700',
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.warning[50],
    borderRadius: 20,
    paddingHorizontal: Platform.OS === 'web' ? 14 : 12,
    paddingVertical: Platform.OS === 'web' ? 6 : 5,
  },
  ratingStar: {
    fontSize: Platform.OS === 'web' ? 16 : 14,
    marginRight: 4,
  },
  ratingValue: {
    fontSize: Platform.OS === 'web' ? 15 : 14,
    fontWeight: '700',
    color: '#92400e',
    marginRight: 4,
  },
  reviewCount: {
    fontSize: Platform.OS === 'web' ? 13 : 12,
    color: '#92400e',
    fontWeight: '600',
  },
  categoryBadge: {
    width: Platform.OS === 'web' ? 56 : 48,
    height: Platform.OS === 'web' ? 56 : 48,
    borderRadius: Platform.OS === 'web' ? 28 : 24,
    backgroundColor: semantic.background,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: semantic.border,
  },
  categoryIcon: {
    fontSize: Platform.OS === 'web' ? 28 : 24,
  },
  // Price Card - Prominent
  priceCard: {
    backgroundColor: semantic.background,
    borderRadius: Platform.OS === 'web' ? 16 : 14,
    padding: Platform.OS === 'web' ? 24 : 20,
    marginBottom: Platform.OS === 'web' ? 24 : 20,
    borderWidth: 2,
    borderColor: semantic.border,
  },
  priceLabel: {
    fontSize: Platform.OS === 'web' ? 13 : 12,
    color: semantic.textSecondary,
    fontWeight: '600',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    flexWrap: 'wrap',
  },
  priceValue: {
    fontSize: Platform.OS === 'web' ? (screenWidth < 768 ? 28 : 36) : 32,
    fontWeight: '800',
    color: semantic.primary,
    letterSpacing: -1,
    marginRight: 8,
  },
  pricingTypeBadge: {
    backgroundColor: colors.primary[100],
    borderRadius: 12,
    paddingHorizontal: Platform.OS === 'web' ? 12 : 10,
    paddingVertical: Platform.OS === 'web' ? 6 : 5,
    alignSelf: 'flex-start',
  },
  pricingTypeText: {
    fontSize: Platform.OS === 'web' ? 13 : 12,
    color: semantic.primary,
    fontWeight: '700',
  },
  // Modern Card Styles
  descriptionCard: {
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? (screenWidth < 768 ? 12 : 16) : 16,
    padding: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 24) : 24,
    marginBottom: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 20) : 20,
    marginHorizontal: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 32) : 20,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 16px rgba(0, 0, 0, 0.08), 0 2px 6px rgba(0, 0, 0, 0.04)',
      borderWidth: 1,
      borderColor: semantic.background,
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    }),
  },
  detailsCard: {
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? (screenWidth < 768 ? 12 : 16) : 16,
    padding: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 24) : 24,
    marginBottom: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 20) : 20,
    marginHorizontal: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 32) : 20,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 16px rgba(0, 0, 0, 0.08), 0 2px 6px rgba(0, 0, 0, 0.04)',
      borderWidth: 1,
      borderColor: semantic.background,
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    }),
  },
  cardTitle: {
    fontSize: Platform.OS === 'web' ? (screenWidth < 768 ? 18 : 22) : 20,
    fontWeight: '800',
    color: colors.neutral[900],
    marginBottom: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 20) : 16,
    letterSpacing: -0.3,
  },
  descriptionText: {
    fontSize: Platform.OS === 'web' ? 16 : 15,
    color: colors.neutral[600],
    lineHeight: Platform.OS === 'web' ? 28 : 24,
    fontWeight: '500',
  },
  detailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Platform.OS === 'web' ? 16 : 12,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: semantic.background,
    borderRadius: Platform.OS === 'web' ? 16 : 14,
    padding: Platform.OS === 'web' ? 20 : 16,
    flex: Platform.OS === 'web' ? 1 : undefined,
    minWidth: Platform.OS === 'web' ? 200 : '100%',
    borderWidth: 1,
    borderColor: semantic.border,
  },
  detailIcon: {
    fontSize: Platform.OS === 'web' ? 28 : 24,
    marginRight: Platform.OS === 'web' ? 16 : 12,
  },
  detailContent: {
    flex: 1,
  },
  detailLabel: {
    fontSize: Platform.OS === 'web' ? 13 : 12,
    color: semantic.textSecondary,
    fontWeight: '600',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  detailValue: {
    fontSize: Platform.OS === 'web' ? 18 : 16,
    color: colors.neutral[900],
    fontWeight: '700',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 12,
  },
  locationCard: {
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? (screenWidth < 768 ? 12 : 16) : 16,
    padding: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 24) : 24,
    marginBottom: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 20) : 20,
    marginHorizontal: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 32) : 20,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 16px rgba(0, 0, 0, 0.08), 0 2px 6px rgba(0, 0, 0, 0.04)',
      borderWidth: 1,
      borderColor: semantic.background,
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    }),
  },
  locationContent: {
    backgroundColor: semantic.background,
    borderRadius: Platform.OS === 'web' ? 12 : 10,
    padding: Platform.OS === 'web' ? 20 : 16,
    borderWidth: 1,
    borderColor: semantic.border,
  },
  locationText: {
    fontSize: Platform.OS === 'web' ? 15 : 14,
    color: colors.neutral[900],
    marginBottom: 8,
    lineHeight: Platform.OS === 'web' ? 24 : 22,
    fontWeight: '600',
  },
  locationCity: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: semantic.textSecondary,
    fontWeight: '500',
  },
  galleryCard: {
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? (screenWidth < 768 ? 12 : 16) : 16,
    padding: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 24) : 24,
    marginBottom: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 20) : 20,
    marginHorizontal: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 32) : 20,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 16px rgba(0, 0, 0, 0.08), 0 2px 6px rgba(0, 0, 0, 0.04)',
      borderWidth: 1,
      borderColor: semantic.background,
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    }),
  },
  galleryScroll: {
    marginTop: 16,
  },
  galleryScrollContent: {
    paddingRight: Platform.OS === 'web' ? 0 : 20,
  },
  galleryImageContainer: {
    marginRight: Platform.OS === 'web' ? 16 : 12,
    borderRadius: Platform.OS === 'web' ? 16 : 12,
    overflow: 'hidden',
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    }),
  },
  galleryImage: {
    width: Platform.OS === 'web' ? 240 : 200,
    height: Platform.OS === 'web' ? 180 : 150,
  },
  reviewsCard: {
    backgroundColor: semantic.surface,
    borderRadius: Platform.OS === 'web' ? (screenWidth < 768 ? 12 : 16) : 16,
    padding: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 24) : 24,
    marginBottom: Platform.OS === 'web' ? (screenWidth < 768 ? 24 : 32) : 32,
    marginTop: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 20) : 20,
    marginHorizontal: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 32) : 20,
    minHeight: 120,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 4px 16px rgba(0, 0, 0, 0.08), 0 2px 6px rgba(0, 0, 0, 0.04)',
      borderWidth: 1,
      borderColor: semantic.background,
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    }),
  },
  reviewsLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    gap: 12,
  },
  reviewsLoadingText: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: semantic.textSecondary,
  },
  reviewsList: {
    marginTop: 16,
    gap: Platform.OS === 'web' ? 20 : 16,
  },
  reviewItem: {
    paddingBottom: Platform.OS === 'web' ? 20 : 16,
    borderBottomWidth: 1,
    borderBottomColor: semantic.border,
  },
  reviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  reviewUserInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  reviewAvatar: {
    width: Platform.OS === 'web' ? 48 : 40,
    height: Platform.OS === 'web' ? 48 : 40,
    borderRadius: Platform.OS === 'web' ? 24 : 20,
    marginRight: 12,
  },
  reviewAvatarPlaceholder: {
    width: Platform.OS === 'web' ? 48 : 40,
    height: Platform.OS === 'web' ? 48 : 40,
    borderRadius: Platform.OS === 'web' ? 24 : 20,
    backgroundColor: semantic.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  reviewAvatarText: {
    color: semantic.surface,
    fontSize: Platform.OS === 'web' ? 18 : 16,
    fontWeight: '700',
  },
  reviewUserDetails: {
    flex: 1,
  },
  reviewUserName: {
    fontSize: Platform.OS === 'web' ? 16 : 15,
    fontWeight: '700',
    color: colors.neutral[900],
    marginBottom: 4,
  },
  reviewDate: {
    fontSize: Platform.OS === 'web' ? 13 : 12,
    color: semantic.textSecondary,
  },
  reviewRating: {
    marginLeft: 12,
  },
  reviewRatingText: {
    fontSize: Platform.OS === 'web' ? 16 : 14,
  },
  reviewComment: {
    fontSize: Platform.OS === 'web' ? 15 : 14,
    color: colors.neutral[700],
    lineHeight: Platform.OS === 'web' ? 24 : 22,
  },
  reviewsEmpty: {
    paddingVertical: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewsEmptyIcon: {
    fontSize: Platform.OS === 'web' ? 48 : 40,
    marginBottom: 12,
  },
  reviewsEmptyText: {
    fontSize: Platform.OS === 'web' ? 15 : 14,
    color: semantic.textSecondary,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  footer: {
    backgroundColor: semantic.surface,
    borderTopWidth: 1,
    borderTopColor: semantic.border,
    paddingHorizontal: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 32) : 20,
    paddingTop: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 20) : 20,
    paddingBottom: Platform.OS === 'web' ? (screenWidth < 768 ? 20 : 24) : (isMobile ? 20 : 24),
    position: 'relative',
    zIndex: 10,
    ...(Platform.OS === 'web' ? {
      boxShadow: screenWidth < 768 ? '0 -2px 8px rgba(0, 0, 0, 0.06)' : '0 -4px 20px rgba(0, 0, 0, 0.08), 0 -2px 8px rgba(0, 0, 0, 0.04)',
    } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 8,
    }),
  },
  footerButtons: {
    flexDirection: 'row',
    gap: Platform.OS === 'web' ? (screenWidth < 768 ? 12 : 16) : 12,
    alignItems: 'stretch',
  },
  modernBookButton: {
    flex: 1,
    backgroundColor: semantic.primary,
    paddingVertical: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 18) : 16,
    paddingHorizontal: Platform.OS === 'web' ? (screenWidth < 768 ? 20 : 32) : 20,
    borderRadius: Platform.OS === 'web' ? (screenWidth < 768 ? 14 : 16) : 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    minHeight: Platform.OS === 'web' ? (screenWidth < 768 ? 56 : 60) : 56,
    gap: 12,
    ...(Platform.OS === 'web' ? {
      boxShadow: screenWidth < 768 ? '0 4px 12px rgba(79, 70, 229, 0.3)' : '0 8px 24px rgba(79, 70, 229, 0.4), 0 4px 8px rgba(79, 70, 229, 0.3)',
      transition: 'all 0.3s ease',
      cursor: 'pointer',
    } : {
      shadowColor: semantic.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 8,
    }),
  },
  modernBookButtonFull: {
    ...(Platform.OS === 'web' ? {
      maxWidth: screenWidth < 768 ? '100%' : 400,
      alignSelf: 'center',
      width: '100%',
    } : {}),
  },
  viewProfileButton: {
    flex: 1,
    backgroundColor: semantic.success,
    paddingVertical: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 18) : 16,
    paddingHorizontal: Platform.OS === 'web' ? (screenWidth < 768 ? 20 : 32) : 20,
    borderRadius: Platform.OS === 'web' ? (screenWidth < 768 ? 14 : 16) : 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    minHeight: Platform.OS === 'web' ? (screenWidth < 768 ? 56 : 60) : 56,
    gap: 12,
    ...(Platform.OS === 'web' ? {
      boxShadow: screenWidth < 768 ? '0 4px 12px rgba(16, 185, 129, 0.3)' : '0 8px 24px rgba(16, 185, 129, 0.4), 0 4px 8px rgba(16, 185, 129, 0.3)',
      transition: 'all 0.3s ease',
      cursor: 'pointer',
    } : {
      shadowColor: semantic.success,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 8,
    }),
  },
  viewProfileButtonIcon: {
    fontSize: Platform.OS === 'web' ? (screenWidth < 768 ? 20 : 24) : 22,
  },
  viewProfileButtonText: {
    color: semantic.surface,
    fontSize: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 20) : 18,
    fontWeight: '800',
    letterSpacing: Platform.OS === 'web' ? (screenWidth < 768 ? 0.3 : 0.5) : 0.3,
  },
  modernBookButtonIcon: {
    fontSize: Platform.OS === 'web' ? (screenWidth < 768 ? 20 : 24) : 22,
  },
  modernBookButtonText: {
    color: semantic.surface,
    fontSize: Platform.OS === 'web' ? (screenWidth < 768 ? 16 : 20) : 18,
    fontWeight: '800',
    letterSpacing: Platform.OS === 'web' ? (screenWidth < 768 ? 0.3 : 0.5) : 0.3,
  },
  bookNowButton: {
    backgroundColor: semantic.primary,
    paddingVertical: isMobile ? 18 : 16,
    borderRadius: isMobile ? 14 : 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: isMobile ? 56 : undefined,
    ...(Platform.OS === 'web' ? {
      boxShadow: '0 6px 20px rgba(99, 102, 241, 0.35), 0 2px 6px rgba(99, 102, 241, 0.25)',
      transition: 'all 0.2s ease',
    } : {
      shadowColor: semantic.primary,
      shadowOffset: { width: 0, height: isMobile ? 6 : 4 },
      shadowOpacity: isMobile ? 0.4 : 0.3,
      shadowRadius: isMobile ? 12 : 8,
      elevation: isMobile ? 8 : 6,
    }),
  },
  bookNowButtonText: {
    color: semantic.surface,
    fontSize: isMobile ? 18 : 16,
    fontWeight: '700',
    letterSpacing: isMobile ? 0.5 : 0.3,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  emptyStateText: {
    fontSize: 16,
    color: semantic.textSecondary,
  },
  // Package styles
  packagesCard: {
    backgroundColor: semantic.surface,
    borderRadius: 16,
    padding: isMobile ? 16 : 20,
    marginBottom: 16,
    ...(Platform.OS === 'web'
      ? { boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08)' }
      : {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.08,
          shadowRadius: 8,
          elevation: 3,
        }),
  },
  packagesSubtitle: {
    fontSize: 13,
    color: semantic.textSecondary,
    marginBottom: 16,
    marginTop: -4,
  },
});
