import { StyleSheet, Platform } from 'react-native';
import { colors, semantic } from '../theme';

export interface BreakpointFlags {
  isMobile: boolean;
  isMobileWeb: boolean;
  isTablet: boolean;
  isDesktop: boolean;
  isLargeDesktop: boolean;
  screenWidth: number;
}

/**
 * Build the full LandingPage StyleSheet.
 * Depends on responsive breakpoint flags, so it must be called inside useMemo.
 */
export const createLandingStyles = ({
  isMobile,
  isMobileWeb,
  isDesktop,
  isLargeDesktop,
  screenWidth,
}: BreakpointFlags) => {
  const isExtraSmall = screenWidth < 360;

  return StyleSheet.create({
    wrapper: {
      flex: 1,
      position: 'relative',
      backgroundColor: semantic.background,
    },
    backgroundContainer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 0,
      overflow: 'hidden',
    },
    backgroundGradient: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: '#F8FAFC',
    },
    backgroundCircle1: {
      position: 'absolute',
      width: isDesktop ? 400 : 280,
      height: isDesktop ? 400 : 280,
      borderRadius: isDesktop ? 200 : 140,
      backgroundColor: 'rgba(37, 99, 235, 0.06)',
      top: -150,
      right: -150,
      ...(Platform.OS === 'web' && { filter: 'blur(60px)' }),
    },
    backgroundCircle2: {
      position: 'absolute',
      width: isDesktop ? 350 : 240,
      height: isDesktop ? 350 : 240,
      borderRadius: isDesktop ? 175 : 120,
      backgroundColor: 'rgba(37, 99, 235, 0.04)',
      bottom: isDesktop ? 150 : 100,
      left: -100,
      ...(Platform.OS === 'web' && { filter: 'blur(50px)' }),
    },
    backgroundCircle3: {
      position: 'absolute',
      width: 0,
      height: 0,
      borderRadius: 0,
      backgroundColor: 'rgba(139, 92, 246, 0.12)',
      top: isDesktop ? '35%' : '30%',
      right: isDesktop ? 30 : 10,
      opacity: 0,
    },
    backgroundCircle4: {
      position: 'absolute',
      width: 0,
      height: 0,
      borderRadius: 0,
      backgroundColor: 'rgba(59, 130, 246, 0.1)',
      top: isDesktop ? '60%' : '55%',
      left: isDesktop ? 100 : 50,
      opacity: 0,
    },
    backgroundCircle5: {
      position: 'absolute',
      width: 0,
      height: 0,
      borderRadius: 0,
      backgroundColor: 'rgba(236, 72, 153, 0.08)',
      bottom: isDesktop ? 300 : 200,
      right: isDesktop ? 200 : 100,
      opacity: 0,
    },
    backgroundPattern: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      opacity: 0,
    },
    backgroundAccent1: {
      position: 'absolute',
      width: isDesktop ? 200 : 150,
      height: isDesktop ? 200 : 150,
      borderRadius: isDesktop ? 100 : 75,
      backgroundColor: 'rgba(34, 197, 94, 0.08)',
      top: isDesktop ? '20%' : '15%',
      left: isDesktop ? '15%' : '10%',
      opacity: 0,
    },
    backgroundAccent2: {
      position: 'absolute',
      width: isDesktop ? 250 : 180,
      height: isDesktop ? 250 : 180,
      borderRadius: isDesktop ? 125 : 90,
      backgroundColor: 'rgba(251, 146, 60, 0.1)',
      bottom: isDesktop ? '25%' : '20%',
      right: isDesktop ? '20%' : '15%',
      opacity: 0,
    },
    container: {
      flex: 1,
      backgroundColor: 'transparent',
      zIndex: 1,
    },
    scrollContent: {
      flexGrow: 1,
      maxWidth: isLargeDesktop ? 1600 : isDesktop ? 1200 : '100%',
      alignSelf: 'center',
      width: '100%',
      backgroundColor: 'transparent',
    },
    topBar: {
      backgroundColor: colors.neutral[100],
      paddingVertical: isMobile || isMobileWeb ? 8 : 10,
      paddingHorizontal: isMobile || isMobileWeb ? 16 : isDesktop ? 60 : 40,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: semantic.border,
    },
    topBarText: {
      fontSize: isMobile ? 12 : 13,
      color: semantic.textSecondary,
    },
    topBarRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
    },
    topBarLink: {
      paddingVertical: 4,
    },
    topBarLinkText: {
      fontSize: isMobile ? 12 : 13,
      color: semantic.primary,
      fontWeight: '500',
    },
    header: {
      backgroundColor: semantic.surface,
      borderBottomWidth: 1,
      borderBottomColor: semantic.border,
      paddingVertical: isMobile || isMobileWeb ? 12 : 16,
      ...(isDesktop && Platform.OS === 'web' && !isMobileWeb
        ? {
            position: 'sticky' as any,
            top: 0,
            zIndex: 1000,
          }
        : {}),
    },
    headerContent: {
      flexDirection: isMobile || isMobileWeb ? 'column' : 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: isMobile || isMobileWeb ? 16 : isDesktop ? 60 : 40,
      gap: isMobile || isMobileWeb ? 16 : 24,
      maxWidth: isLargeDesktop ? 1600 : isDesktop ? 1200 : '100%',
      alignSelf: 'center',
      width: '100%',
    },
    searchBarContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: isMobile || isMobileWeb ? 1 : 0.3,
      backgroundColor: semantic.background,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: semantic.border,
      paddingHorizontal: 12,
      height: isMobileWeb ? 36 : 40,
    },
    searchIconButton: { paddingRight: 8 },
    searchIcon: { fontSize: 18, color: semantic.textSecondary },
    logoSection: {
      flex: isMobile ? 1 : 0.4,
      alignItems: 'center',
    },
    logo: {
      fontSize: isMobile || isMobileWeb ? 28 : isDesktop ? 32 : 30,
      fontWeight: '900',
      color: semantic.textPrimary,
      letterSpacing: 2,
    },
    headerNav: {
      flex: isMobile || isMobileWeb ? 1 : 0.3,
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      gap: isMobile || isMobileWeb ? 8 : 16,
      flexWrap: 'wrap',
    },
    headerNavItem: {
      paddingVertical: 6,
      paddingHorizontal: isMobile || isMobileWeb ? 8 : 12,
    },
    headerNavItemActive: {
      borderBottomWidth: 2,
      borderBottomColor: semantic.primary,
    },
    headerNavText: {
      fontSize: isMobile ? 13 : 14,
      color: semantic.textSecondary,
      fontWeight: '500',
    },
    headerNavTextActive: {
      color: semantic.primary,
      fontWeight: '600',
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: semantic.textPrimary,
      padding: 0,
    },
    heroSection: {
      paddingHorizontal: isMobile || isMobileWeb ? 16 : isDesktop ? 60 : 40,
      paddingVertical: isMobile || isMobileWeb ? 40 : isDesktop ? 60 : 50,
      backgroundColor: semantic.surface,
      maxWidth: isLargeDesktop ? 1600 : isDesktop ? 1200 : '100%',
      alignSelf: 'center',
      width: '100%',
    },
    heroContent: {
      flexDirection: isMobile || isMobileWeb ? 'column' : 'row',
      alignItems: 'center',
      gap: isMobile || isMobileWeb ? 24 : isDesktop ? 40 : 32,
    },
    heroTextContainer: { flex: 1 },
    heroBadge: {
      fontSize: isMobile ? 12 : 14,
      color: semantic.primary,
      fontWeight: '600',
      marginBottom: 12,
      letterSpacing: 1,
    },
    heroTitle: {
      fontSize: isExtraSmall ? 24 : isMobile || isMobileWeb ? 28 : isDesktop ? 48 : 40,
      fontWeight: '700',
      color: semantic.textPrimary,
      marginBottom: 16,
      lineHeight: isExtraSmall ? 32 : isMobile || isMobileWeb ? 36 : isDesktop ? 56 : 48,
    },
    heroDescription: {
      fontSize: isMobile || isMobileWeb ? 16 : 18,
      color: semantic.textSecondary,
      lineHeight: isMobile || isMobileWeb ? 24 : 28,
      marginBottom: 24,
    },
    heroCTA: {
      alignSelf: 'flex-start',
      paddingVertical: 14,
      paddingHorizontal: 32,
      backgroundColor: semantic.primary,
      borderRadius: 8,
    },
    heroCTAText: { color: semantic.surface, fontSize: 16, fontWeight: '600' },
    heroImages: {
      flex: 1,
      flexDirection: 'row',
      gap: 16,
      justifyContent: 'center',
      maxWidth: isMobile ? '100%' : undefined,
    },
    heroImage1: {
      width: isMobile ? '100%' : isDesktop ? 280 : 240,
      maxWidth: isMobile ? undefined : isDesktop ? 280 : 240,
      height: isMobile ? 200 : isDesktop ? 350 : 300,
      borderRadius: 12,
      backgroundColor: semantic.border,
    },
    heroImage2: {
      width: isMobile ? '100%' : isDesktop ? 240 : 200,
      maxWidth: isMobile ? undefined : isDesktop ? 240 : 200,
      height: isMobile ? 180 : isDesktop ? 320 : 280,
      borderRadius: 12,
      backgroundColor: semantic.border,
      marginTop: isMobile ? 0 : 40,
    },
    heroImagePlaceholder: {
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: semantic.primary,
    },
    heroImageText: { color: semantic.surface, fontSize: 18, fontWeight: '600' },
    contentWithSidebar: {
      flexDirection: isMobile ? 'column' : 'row',
      paddingHorizontal: isMobile ? 16 : isDesktop ? 60 : 40,
      paddingVertical: isMobile ? 32 : isDesktop ? 48 : 32,
      gap: isMobile ? 24 : isDesktop ? 32 : 24,
      maxWidth: isLargeDesktop ? 1600 : isDesktop ? 1200 : '100%',
      alignSelf: 'center',
      width: '100%',
    },
    mainContentArea: { flex: isMobile ? 1 : 2 },
    recommendedSection: { marginBottom: isMobile ? 32 : isDesktop ? 48 : 40 },
    recommendedTitle: {
      fontSize: isExtraSmall ? 22 : isMobile ? 26 : isDesktop ? 36 : 32,
      fontWeight: '700',
      color: semantic.textPrimary,
      marginBottom: 8,
    },
    recommendedSubtitle: {
      fontSize: isMobile ? 14 : 16,
      color: semantic.textSecondary,
      marginBottom: 24,
    },
    mainContent: {
      paddingHorizontal: isMobile ? 16 : isDesktop ? 60 : 40,
      paddingVertical: isMobile ? 32 : isDesktop ? 48 : 32,
      maxWidth: isLargeDesktop ? 1600 : isDesktop ? 1200 : '100%',
      alignSelf: 'center',
      width: '100%',
    },
    loadingContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 60 },
    loadingText: { marginTop: 12, fontSize: 14, color: semantic.textSecondary },
    featuredSection: {
      flexDirection: isMobile ? 'column' : 'row',
      gap: isMobile ? 16 : isDesktop ? 32 : 24,
      marginBottom: isMobile ? 32 : isDesktop ? 64 : 48,
    },
    featuredCard: {
      flex: 2,
      backgroundColor: semantic.surface,
      borderRadius: 12,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: semantic.border,
      elevation: 2,
      ...(Platform.OS !== 'web' && {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
      }),
      ...(Platform.OS === 'web' && {
        boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
      }),
    },
    featuredImageContainer: {
      position: 'relative',
      height: isMobile ? 200 : 300,
      backgroundColor: semantic.primary,
    },
    featuredTag: {
      position: 'absolute',
      top: 16,
      right: 16,
      backgroundColor: colors.warning[50],
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 4,
      zIndex: 1,
    },
    featuredTagText: {
      color: semantic.textPrimary,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.5,
    },
    featuredImage: { width: '100%', height: '100%' },
    featuredImagePlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    featuredImageText: { color: semantic.surface, fontSize: 18, fontWeight: '600' },
    featuredContent: { padding: isMobile ? 16 : 24 },
    featuredTitle: {
      fontSize: isExtraSmall ? 18 : isMobile ? 22 : 32,
      fontWeight: '700',
      color: semantic.textPrimary,
      marginBottom: 12,
    },
    featuredDescription: {
      fontSize: 16,
      color: semantic.textSecondary,
      lineHeight: 24,
      marginBottom: 16,
    },
    featuredMeta: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    featuredPrice: { fontSize: 20, fontWeight: '700', color: semantic.primary },
    featuredRating: { fontSize: 14, color: semantic.textSecondary },
    exploreButton: {
      alignSelf: 'flex-start',
      paddingVertical: 12,
      paddingHorizontal: 24,
      backgroundColor: semantic.primary,
      borderRadius: 8,
    },
    exploreButtonText: { color: semantic.surface, fontSize: 14, fontWeight: '600' },
    sidebar: {
      flex: isMobile ? 1 : 0.4,
      minWidth: isMobile ? '100%' : isDesktop ? 320 : 280,
    },
    sidebarPromoImage: {
      width: '100%',
      height: isMobile ? 200 : isDesktop ? 250 : 220,
      borderRadius: 12,
      overflow: 'hidden',
      marginBottom: 20,
      backgroundColor: semantic.border,
    },
    sidebarImage: { width: '100%', height: '100%' },
    sidebarImagePlaceholder: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: semantic.primary,
    },
    sidebarImageText: { color: semantic.surface, fontSize: 18, fontWeight: '600' },
    sidebarPromo: {
      backgroundColor: semantic.surface,
      borderRadius: 12,
      padding: 20,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: semantic.border,
    },
    sidebarPromoTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: semantic.textPrimary,
      marginBottom: 12,
    },
    sidebarPromoText: {
      fontSize: 14,
      color: semantic.textSecondary,
      lineHeight: 20,
      marginBottom: 16,
    },
    sidebarPromoButton: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      backgroundColor: semantic.primary,
      borderRadius: 8,
      alignSelf: 'flex-start',
    },
    sidebarPromoButtonText: { color: semantic.surface, fontSize: 14, fontWeight: '600' },
    sidebarFeatures: { gap: 16, marginBottom: 20 },
    sidebarFeature: {
      flexDirection: 'row',
      gap: 12,
      backgroundColor: semantic.surface,
      borderRadius: 12,
      padding: 16,
      borderWidth: 1,
      borderColor: semantic.border,
    },
    sidebarFeatureIcon: { fontSize: 24 },
    sidebarFeatureContent: { flex: 1 },
    sidebarFeatureTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: semantic.textPrimary,
      marginBottom: 6,
    },
    sidebarFeatureText: { fontSize: 13, color: semantic.textSecondary, lineHeight: 18 },
    sidebarNewsletter: { backgroundColor: semantic.primary, borderRadius: 12, padding: 24 },
    sidebarNewsletterTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: semantic.surface,
      marginBottom: 8,
    },
    sidebarNewsletterSubtitle: {
      fontSize: 14,
      color: 'rgba(255, 255, 255, 0.9)',
      marginBottom: 16,
    },
    sidebarNewsletterForm: { gap: 12 },
    sidebarNewsletterInput: {
      backgroundColor: semantic.surface,
      borderRadius: 8,
      paddingVertical: 12,
      paddingHorizontal: 16,
      fontSize: 14,
      color: semantic.textPrimary,
    },
    sidebarNewsletterButton: {
      paddingVertical: 12,
      paddingHorizontal: 20,
      backgroundColor: semantic.surface,
      borderRadius: 8,
      alignItems: 'center',
    },
    sidebarNewsletterButtonText: { color: semantic.primary, fontSize: 14, fontWeight: '600' },
    sidebarHeader: { marginBottom: 16 },
    sidebarTitle: { fontSize: 20, fontWeight: '700', color: semantic.textPrimary },
    tabContainer: { flexDirection: 'row', gap: 8, marginBottom: 20 },
    tab: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 6,
      backgroundColor: semantic.surface,
    },
    tabActive: { backgroundColor: semantic.primary },
    tabText: { fontSize: 13, color: semantic.textSecondary, fontWeight: '600' },
    tabTextActive: { color: semantic.surface, fontWeight: '700' },
    sidebarLoading: { padding: 20, alignItems: 'center' },
    articleList: { gap: 16 },
    articleItem: {
      flexDirection: 'row',
      gap: 12,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: semantic.border,
    },
    articleThumbnail: {
      width: 60,
      height: 60,
      borderRadius: 8,
      backgroundColor: semantic.primary,
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
    },
    articleThumbnailImage: { width: '100%', height: '100%' },
    articleThumbnailText: { color: semantic.surface, fontSize: 18, fontWeight: '700' },
    articleInfo: { flex: 1, justifyContent: 'center' },
    articleTitle: { fontSize: 14, fontWeight: '600', color: semantic.textPrimary, marginBottom: 4 },
    articleCategory: { fontSize: 12, color: semantic.textSecondary },
    entertainmentSection: { marginBottom: 48 },
    sectionHeader: { marginBottom: 24 },
    sectionTitle: {
      fontSize: isExtraSmall ? 18 : isMobile ? 22 : 28,
      fontWeight: '700',
      color: semantic.textPrimary,
      alignSelf: 'flex-start',
      borderBottomWidth: 3,
      borderBottomColor: '#2563EB',
      paddingBottom: 4,
    },
    articlesGrid: {
      flexDirection: isMobile ? 'column' : 'row',
      gap: isMobile ? 16 : isDesktop ? 24 : 20,
      flexWrap: 'wrap',
      justifyContent: isDesktop ? 'flex-start' : 'center',
    },
    articleCard: {
      ...(isMobile ? { flex: 1 } : {}),
      ...(Platform.OS === 'web' && !isMobile
        ? {
            width: (isDesktop ? 'calc(33.333% - 16px)' : 'calc(50% - 12px)') as any,
          }
        : {}),
      minWidth: isMobile ? '100%' : isDesktop ? 300 : 280,
      maxWidth: isMobile ? '100%' : isDesktop ? 380 : 320,
      backgroundColor: semantic.surface,
      borderRadius: 12,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: semantic.border,
      elevation: 3,
      ...(Platform.OS !== 'web' && {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.12,
        shadowRadius: 10,
      }),
      ...(Platform.OS === 'web' && {
        boxShadow: '0 3px 15px rgba(0, 0, 0, 0.08)',
        transition: 'transform 0.2s ease, box-shadow 0.2s ease',
      }),
    },
    articleImage: { width: '100%', height: 180 },
    articleImagePlaceholder: {
      height: 180,
      backgroundColor: semantic.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    articleImageText: { color: semantic.surface, fontSize: 16, fontWeight: '600' },
    articleCardContent: { padding: 16 },
    articleCardTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: semantic.textPrimary,
      marginBottom: 8,
    },
    articleCardMeta: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    articleCardPrice: { fontSize: 14, fontWeight: '600', color: semantic.primary },
    articleCardRating: { fontSize: 12, color: semantic.textSecondary },
    categoriesSection: { marginBottom: 48 },
    categoriesGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    categoryCard: {
      paddingVertical: 12,
      paddingHorizontal: 24,
      backgroundColor: semantic.background,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: semantic.border,
      alignItems: 'center',
    },
    categoryCardActive: { backgroundColor: semantic.primary, borderColor: semantic.primary },
    categoryText: { fontSize: 14, fontWeight: '600', color: semantic.textPrimary },
    categoryTextActive: { color: semantic.surface },
    categoryCount: { fontSize: 11, color: semantic.textSecondary, marginTop: 4 },
    ctaSection: {
      backgroundColor: semantic.background,
      borderRadius: 12,
      padding: isMobile ? 24 : 40,
      alignItems: 'center',
      marginBottom: 48,
      borderWidth: 1,
      borderColor: semantic.border,
    },
    ctaTitle: {
      fontSize: isExtraSmall ? 22 : isMobile ? 26 : 36,
      fontWeight: '700',
      color: semantic.textPrimary,
      marginBottom: 12,
      textAlign: 'center',
    },
    ctaDescription: {
      fontSize: 16,
      color: semantic.textSecondary,
      marginBottom: 24,
      textAlign: 'center',
    },
    ctaButtons: {
      flexDirection: isMobileWeb ? 'column' : 'row',
      gap: isMobileWeb ? 12 : 16,
      width: isMobileWeb ? '100%' : 'auto',
    },
    ctaButtonPrimary: {
      paddingVertical: isMobileWeb ? 12 : 14,
      paddingHorizontal: isMobileWeb ? 24 : 32,
      backgroundColor: semantic.primary,
      borderRadius: 8,
      width: isMobileWeb ? '100%' : 'auto',
    },
    ctaButtonSecondary: {
      paddingVertical: isMobileWeb ? 12 : 14,
      paddingHorizontal: isMobileWeb ? 24 : 32,
      backgroundColor: semantic.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: semantic.primary,
      width: isMobileWeb ? '100%' : 'auto',
    },
    ctaButtonText: {
      color: semantic.surface,
      fontSize: isMobileWeb ? 14 : 16,
      fontWeight: '600',
      textAlign: 'center',
    },
    ctaButtonTextSecondary: {
      color: semantic.primary,
      fontSize: isMobileWeb ? 14 : 16,
      fontWeight: '600',
      textAlign: 'center',
    },
    emptyText: { textAlign: 'center', color: semantic.textSecondary, fontSize: 14, padding: 20 },
    footer: {
      backgroundColor: semantic.textPrimary,
      paddingTop: isMobile || isMobileWeb ? 40 : isDesktop ? 60 : 50,
      paddingBottom: isMobile || isMobileWeb ? 24 : isDesktop ? 32 : 28,
      paddingHorizontal: isMobile || isMobileWeb ? 16 : isDesktop ? 60 : 40,
      marginTop: isDesktop ? 64 : 32,
    },
    footerContent: {
      flexDirection: isMobile || isMobileWeb ? 'column' : 'row',
      justifyContent: 'space-between',
      gap: isMobile || isMobileWeb ? 32 : isDesktop ? 48 : 40,
      marginBottom: isMobile || isMobileWeb ? 24 : isDesktop ? 32 : 28,
      maxWidth: isLargeDesktop ? 1600 : isDesktop ? 1200 : '100%',
      alignSelf: 'center',
      width: '100%',
    },
    footerColumn: {
      flex: 1,
      minWidth: isMobile || isMobileWeb ? '100%' : isDesktop ? 200 : 180,
    },
    footerColumnTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: semantic.surface,
      marginBottom: 16,
    },
    footerLink: {
      fontSize: 14,
      color: 'rgba(255, 255, 255, 0.7)',
      marginBottom: 12,
      ...(Platform.OS === 'web' && { cursor: 'pointer', transition: 'color 0.2s ease' }),
    },
    qrCodeContainer: { alignItems: 'center', marginTop: 8 },
    qrCode: {
      width: isMobile || isMobileWeb ? 140 : 160,
      height: isMobile || isMobileWeb ? 140 : 160,
      backgroundColor: semantic.surface,
      borderRadius: 12,
      padding: 12,
      marginBottom: 12,
      ...(Platform.OS === 'web'
        ? { boxShadow: '0 2px 8px rgba(0, 0, 0, 0.15)' }
        : {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 3,
          }),
    },
    qrCodeLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: semantic.surface,
      marginBottom: 4,
      textAlign: 'center',
    },
    qrCodeSubLabel: {
      fontSize: 11,
      color: 'rgba(255, 255, 255, 0.6)',
      marginBottom: 12,
      textAlign: 'center',
    },
    downloadButton: {
      backgroundColor: semantic.success,
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 8,
      ...(Platform.OS === 'web'
        ? { cursor: 'pointer', transition: 'all 0.2s ease' }
        : {
            shadowColor: '#10B981',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 4,
            elevation: 3,
          }),
    },
    downloadButtonText: {
      color: semantic.surface,
      fontSize: 13,
      fontWeight: '600',
      textAlign: 'center',
    },
    footerBottom: {
      borderTopWidth: 1,
      borderTopColor: 'rgba(255, 255, 255, 0.1)',
      paddingTop: isMobile || isMobileWeb ? 20 : isDesktop ? 24 : 22,
      alignItems: 'center',
      maxWidth: isLargeDesktop ? 1600 : isDesktop ? 1200 : '100%',
      alignSelf: 'center',
      width: '100%',
    },
    footerText: { color: 'rgba(255, 255, 255, 0.6)', fontSize: isMobile || isMobileWeb ? 13 : 14 },
    servicesGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: isMobile ? 16 : isDesktop ? 24 : 20,
      justifyContent: isDesktop ? 'flex-start' : 'center',
    },
    serviceCard: {
      ...(isMobile ? { flex: 1 } : {}),
      ...(Platform.OS === 'web' && !isMobile
        ? { width: (isDesktop ? 'calc(33.333% - 16px)' : 'calc(50% - 10px)') as any }
        : {}),
      minWidth: isMobile ? '100%' : isDesktop ? 300 : 280,
      maxWidth: isMobile ? '100%' : isDesktop ? 380 : 320,
      backgroundColor: semantic.surface,
      borderRadius: 12,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: semantic.border,
      elevation: 3,
      ...(Platform.OS !== 'web' && {
        shadowColor: semantic.primary,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.12,
        shadowRadius: 10,
      }),
      ...(Platform.OS === 'web' && {
        boxShadow: '0 3px 15px rgba(37, 99, 235, 0.1)',
        transition: 'transform 0.2s ease, box-shadow 0.2s ease',
      }),
    },
    serviceCardImage: { width: '100%', height: 200 },
    serviceCardImagePlaceholder: {
      width: '100%',
      height: 200,
      backgroundColor: semantic.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    serviceCardImageText: { color: semantic.surface, fontSize: 16, fontWeight: '600' },
    serviceCardContent: { padding: 16 },
    serviceCardTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: semantic.textPrimary,
      marginBottom: 8,
    },
    serviceCardDescription: {
      fontSize: 14,
      color: semantic.textSecondary,
      marginBottom: 12,
      lineHeight: 20,
    },
    serviceCardMeta: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    serviceCardPrice: { fontSize: 18, fontWeight: '700', color: semantic.primary, marginBottom: 8 },
    serviceCardBrand: {
      fontSize: 12,
      color: semantic.textSecondary,
      marginTop: 4,
      fontStyle: 'italic',
    },
    serviceCardRating: { fontSize: 14, color: semantic.textSecondary },
    loadMoreButton: {
      marginTop: 24,
      paddingVertical: 14,
      paddingHorizontal: 32,
      backgroundColor: semantic.primary,
      borderRadius: 8,
      alignSelf: 'center',
    },
    loadMoreButtonText: { color: semantic.surface, fontSize: 16, fontWeight: '600' },
    eventsSection: { marginBottom: 48 },
    eventsContent: { marginTop: 24 },
    eventsDescription: {
      fontSize: 16,
      color: semantic.textSecondary,
      lineHeight: 24,
      marginBottom: 24,
      textAlign: 'center',
    },
    eventsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 20 },
    eventCard: {
      flex: isMobile ? 1 : 1,
      minWidth: isMobile ? '100%' : 280,
      backgroundColor: semantic.surface,
      borderRadius: 12,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: semantic.border,
      elevation: 2,
      ...(Platform.OS !== 'web' && {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
      }),
      ...(Platform.OS === 'web' && { boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)' }),
    },
    eventCardImage: { width: '100%', height: 180 },
    eventCardImagePlaceholder: {
      width: '100%',
      height: 180,
      backgroundColor: semantic.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    eventCardImageText: { color: semantic.surface, fontSize: 16, fontWeight: '600' },
    eventCardContent: { padding: 16 },
    eventCardTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: semantic.textPrimary,
      marginBottom: 8,
    },
    eventCardCategory: { fontSize: 14, color: semantic.textSecondary },
    aboutSection: { marginBottom: 48 },
    aboutContent: { marginTop: 24 },
    aboutText: {
      fontSize: 16,
      color: semantic.textSecondary,
      lineHeight: 24,
      marginBottom: 32,
      textAlign: 'center',
    },
    aboutFeatures: { flexDirection: isMobile ? 'column' : 'row', gap: 24, flexWrap: 'wrap' },
    aboutFeature: {
      flex: isMobile ? 1 : 1,
      minWidth: isMobile ? '100%' : 250,
      alignItems: 'center',
      padding: 24,
      backgroundColor: semantic.background,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: semantic.border,
    },
    aboutFeatureIcon: { fontSize: 48, marginBottom: 16 },
    aboutFeatureTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: semantic.textPrimary,
      marginBottom: 8,
    },
    aboutFeatureText: {
      fontSize: 14,
      color: semantic.textSecondary,
      textAlign: 'center',
      lineHeight: 20,
    },
    contactSection: { marginBottom: 48 },
    contactContent: { marginTop: 24 },
    contactDescription: {
      fontSize: 16,
      color: semantic.textSecondary,
      lineHeight: 24,
      marginBottom: 32,
      textAlign: 'center',
    },
    contactInfo: {
      flexDirection: isMobile || isMobileWeb ? 'column' : 'row',
      gap: 24,
      marginBottom: 32,
      flexWrap: 'wrap',
    },
    contactItem: {
      flex: 1,
      minWidth: isMobile || isMobileWeb ? '100%' : 200,
      alignItems: 'center',
      padding: isMobileWeb ? 20 : 24,
      backgroundColor: semantic.background,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: semantic.border,
    },
    contactIcon: { fontSize: 32, marginBottom: 12 },
    contactLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: semantic.textSecondary,
      marginBottom: 8,
    },
    contactValue: {
      fontSize: 16,
      fontWeight: '600',
      color: semantic.textPrimary,
      textAlign: 'center',
    },
    contactButton: {
      alignSelf: 'center',
      paddingVertical: 14,
      paddingHorizontal: 32,
      backgroundColor: semantic.primary,
      borderRadius: 8,
    },
    contactButtonText: { color: semantic.surface, fontSize: 16, fontWeight: '600' },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: Platform.OS === 'web' ? 20 : 16,
      ...(Platform.OS === 'web'
        ? { position: 'fixed' as any, top: 0, left: 0, right: 0, bottom: 0 }
        : {}),
    },
    modalContent: {
      backgroundColor: semantic.surface,
      borderRadius: Platform.OS === 'web' ? 20 : 16,
      width: Platform.OS === 'web' ? '90%' : '100%',
      maxWidth: isMobile ? screenWidth - 32 : 520,
      maxHeight: Platform.OS === 'web' ? ('90vh' as any) : '90%',
      overflow: 'hidden',
      position: 'relative',
      ...(Platform.OS === 'web'
        ? { boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3), 0 4px 16px rgba(0, 0, 0, 0.15)' }
        : {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.25,
            shadowRadius: 24,
            elevation: 10,
          }),
    },
    modalScrollView: { flex: 1 },
    modalScrollContent: { flexGrow: 1, paddingBottom: 20 },
    modalCloseButton: {
      position: 'absolute',
      top: Platform.OS === 'web' ? 16 : 12,
      right: Platform.OS === 'web' ? 16 : 12,
      zIndex: 10,
      padding: 8,
      backgroundColor: 'rgba(0, 0, 0, 0.05)',
      borderRadius: 20,
      width: 36,
      height: 36,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalCloseIcon: {
      fontSize: Platform.OS === 'web' ? 20 : 18,
      color: semantic.textSecondary,
      fontWeight: 'bold',
    },
    modalPlaceholder: { padding: 40, alignItems: 'center' },
    modalPlaceholderText: {
      fontSize: 16,
      color: semantic.textSecondary,
      marginBottom: 20,
      textAlign: 'center',
    },
    modalButton: {
      backgroundColor: colors.primary[500],
      paddingVertical: 12,
      paddingHorizontal: 24,
      borderRadius: 10,
    },
    modalButtonText: { color: semantic.surface, fontSize: 16, fontWeight: '600' },
    // Hamburger menu styles
    hamburgerButton: { padding: 8 },
    hamburgerLine: {
      width: 24,
      height: 2,
      backgroundColor: semantic.textPrimary,
      marginVertical: 3,
      borderRadius: 1,
    },
    mobileMenuOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.3)',
      zIndex: 999,
    },
    mobileMenu: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      width: Math.min(260, screenWidth * 0.8),
      backgroundColor: semantic.surface,
      paddingTop: 60,
      paddingHorizontal: 24,
      zIndex: 1000,
      ...(Platform.OS === 'web'
        ? { boxShadow: '-4px 0 16px rgba(0,0,0,0.1)' }
        : {
            shadowColor: '#000',
            shadowOffset: { width: -4, height: 0 },
            shadowOpacity: 0.1,
            shadowRadius: 16,
            elevation: 10,
          }),
    },
    mobileMenuItem: {
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: semantic.border,
    },
    mobileMenuItemActive: { borderBottomColor: semantic.primary },
    mobileMenuText: { fontSize: 16, color: semantic.textSecondary, fontWeight: '500' },
    mobileMenuTextActive: { color: semantic.primary, fontWeight: '600' },
    mobileMenuClose: { position: 'absolute', top: 16, right: 16, padding: 8 },
    mobileMenuCloseText: { fontSize: 24, color: semantic.textSecondary },
  });
};
