import { StyleSheet, Platform } from 'react-native';

export interface BreakpointFlags {
  isMobile: boolean;
  isMobileWeb: boolean;
  isTablet: boolean;
  isDesktop: boolean;
  isLargeDesktop: boolean;
  screenWidth: number;
}

export const createLandingStyles = ({
  isMobile,
  isMobileWeb,
  isDesktop,
  isLargeDesktop,
  screenWidth,
}: BreakpointFlags) => {
  const isExtraSmall = screenWidth < 360;
  const maxW = isLargeDesktop ? 1200 : isDesktop ? 1080 : '100%';
  const px = isMobile || isMobileWeb ? 16 : isDesktop ? 48 : 32;

  return StyleSheet.create({
    wrapper: {
      flex: 1,
      backgroundColor: '#F8FAFC',
    },
    // Background — no decorative circles
    backgroundContainer: { display: 'none' },
    backgroundGradient: { display: 'none' },
    backgroundCircle1: { display: 'none' },
    backgroundCircle2: { display: 'none' },
    backgroundCircle3: { display: 'none' },
    backgroundCircle4: { display: 'none' },
    backgroundCircle5: { display: 'none' },
    backgroundPattern: { display: 'none' },
    backgroundAccent1: { display: 'none' },
    backgroundAccent2: { display: 'none' },

    container: { flex: 1 },
    scrollContent: {
      flexGrow: 1,
      maxWidth: maxW,
      alignSelf: 'center',
      width: '100%',
    },

    // ── NavBar ──
    topBar: { display: 'none' },
    topBarText: { display: 'none' },
    topBarRight: { display: 'none' },
    topBarLink: { display: 'none' },
    topBarLinkText: { display: 'none' },

    header: {
      backgroundColor: '#FFFFFF',
      borderBottomWidth: 1,
      borderBottomColor: '#E2E8F0',
      paddingVertical: 12,
      ...(isDesktop && Platform.OS === 'web' && !isMobileWeb
        ? { position: 'sticky' as any, top: 0, zIndex: 1000 }
        : {}),
    },
    headerContent: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: px,
      maxWidth: maxW,
      alignSelf: 'center',
      width: '100%',
    },
    logoSection: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    logo: {
      fontSize: 20,
      fontWeight: '700',
      color: '#0F172A',
      letterSpacing: -0.3,
    },
    logoDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#2563EB',
      marginRight: 10,
    },
    headerNav: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    headerNavItem: {
      paddingVertical: 6,
      paddingHorizontal: 12,
    },
    headerNavItemActive: {},
    headerNavText: {
      fontSize: 14,
      color: '#64748B',
      fontWeight: '500',
    },
    headerNavTextActive: {
      color: '#0F172A',
      fontWeight: '600',
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    loginOutlineButton: {
      paddingVertical: 8,
      paddingHorizontal: 18,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      backgroundColor: '#FFFFFF',
    },
    loginOutlineText: {
      fontSize: 14,
      color: '#334155',
      fontWeight: '600',
    },
    getStartedButton: {
      paddingVertical: 8,
      paddingHorizontal: 18,
      borderRadius: 10,
      backgroundColor: '#0F172A',
    },
    getStartedText: {
      fontSize: 14,
      color: '#FFFFFF',
      fontWeight: '600',
    },
    searchBarContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      paddingHorizontal: 14,
      height: 44,
      flex: 1,
      maxWidth: 480,
    },
    searchIconButton: { paddingRight: 10 },
    searchIcon: { fontSize: 18, color: '#94A3B8' },
    searchInput: {
      flex: 1,
      fontSize: 15,
      color: '#0F172A',
      padding: 0,
      ...(Platform.OS === 'web' ? { outlineStyle: 'none' as any } : {}),
    },

    // ── Hero ──
    heroSection: {
      paddingHorizontal: px,
      paddingVertical: isMobile || isMobileWeb ? 48 : 80,
      backgroundColor: '#FFFFFF',
      borderBottomWidth: 1,
      borderBottomColor: '#E2E8F0',
      alignItems: 'center',
    },
    heroContent: {
      alignItems: 'center',
      maxWidth: 640,
      width: '100%',
    },
    heroTextContainer: { alignItems: 'center', width: '100%' },
    heroBadge: { display: 'none' },
    heroTitle: {
      fontSize: isExtraSmall ? 28 : isMobile || isMobileWeb ? 32 : 48,
      fontWeight: '700',
      color: '#0F172A',
      marginBottom: 16,
      lineHeight: isExtraSmall ? 36 : isMobile || isMobileWeb ? 40 : 56,
      textAlign: 'center',
      letterSpacing: -0.5,
    },
    heroDescription: {
      fontSize: isMobile || isMobileWeb ? 16 : 18,
      color: '#64748B',
      lineHeight: isMobile || isMobileWeb ? 24 : 28,
      marginBottom: 32,
      textAlign: 'center',
    },
    heroCTA: {
      paddingVertical: 14,
      paddingHorizontal: 32,
      backgroundColor: '#0F172A',
      borderRadius: 10,
    },
    heroCTAText: { color: '#FFFFFF', fontSize: 15, fontWeight: '600' },
    heroImages: { display: 'none' },
    heroImage1: { display: 'none' },
    heroImage2: { display: 'none' },
    heroImagePlaceholder: { display: 'none' },
    heroImageText: { display: 'none' },
    heroSearchBar: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      paddingHorizontal: 16,
      height: 52,
      width: '100%',
      maxWidth: 520,
      ...(Platform.OS === 'web'
        ? { boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.04)' }
        : { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 3, elevation: 2 }),
    },

    // ── Main content ──
    mainContent: {
      paddingHorizontal: px,
      paddingVertical: isMobile ? 32 : 48,
      maxWidth: maxW,
      alignSelf: 'center',
      width: '100%',
    },
    loadingContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 60 },
    loadingText: { marginTop: 12, fontSize: 14, color: '#64748B' },

    // ── Content with sidebar ──
    contentWithSidebar: {
      flexDirection: isMobile ? 'column' : 'row',
      gap: isMobile ? 24 : 32,
      marginBottom: 48,
    },
    mainContentArea: { flex: isMobile ? 1 : 2 },
    recommendedSection: { marginBottom: 32 },
    recommendedTitle: {
      fontSize: isExtraSmall ? 20 : isMobile ? 22 : 28,
      fontWeight: '700',
      color: '#0F172A',
      marginBottom: 8,
    },
    recommendedSubtitle: {
      fontSize: isMobile ? 14 : 15,
      color: '#64748B',
      marginBottom: 24,
    },

    // ── Section headers ──
    sectionHeader: { marginBottom: 24 },
    sectionTitle: {
      fontSize: isExtraSmall ? 18 : isMobile ? 22 : 28,
      fontWeight: '700',
      color: '#0F172A',
      alignSelf: 'flex-start',
    },

    // ── Service cards ──
    servicesGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 16,
      justifyContent: isDesktop ? 'flex-start' : 'center',
    },
    serviceCard: {
      ...(isMobile ? { flex: 1 } : {}),
      ...(Platform.OS === 'web' && !isMobile
        ? { width: (isDesktop ? 'calc(33.333% - 11px)' : 'calc(50% - 8px)') as any }
        : {}),
      minWidth: isMobile ? '100%' : 280,
      maxWidth: isMobile ? '100%' : 380,
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: '#E2E8F0',
      ...(Platform.OS === 'web'
        ? { boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.04)', transition: 'box-shadow 0.15s ease' }
        : { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 3, elevation: 2 }),
    },
    serviceCardImage: { width: '100%', height: 180 },
    serviceCardImagePlaceholder: {
      width: '100%',
      height: 180,
      backgroundColor: '#EFF6FF',
      justifyContent: 'center',
      alignItems: 'center',
    },
    serviceCardImageText: { color: '#2563EB', fontSize: 16, fontWeight: '600' },
    serviceCardContent: { padding: 16 },
    serviceCardTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: '#0F172A',
      marginBottom: 6,
    },
    serviceCardDescription: {
      fontSize: 14,
      color: '#64748B',
      marginBottom: 12,
      lineHeight: 20,
    },
    serviceCardMeta: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    serviceCardPrice: { fontSize: 16, fontWeight: '700', color: '#0F172A', marginBottom: 4 },
    serviceCardBrand: {
      fontSize: 12,
      color: '#94A3B8',
      marginTop: 4,
    },
    serviceCardRating: { fontSize: 13, color: '#64748B' },

    // ── Categories ──
    categoriesSection: { marginBottom: 48 },
    categoriesGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    categoryCard: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      backgroundColor: '#FFFFFF',
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      alignItems: 'center',
    },
    categoryCardActive: { backgroundColor: '#0F172A', borderColor: '#0F172A' },
    categoryText: { fontSize: 14, fontWeight: '500', color: '#334155' },
    categoryTextActive: { color: '#FFFFFF' },
    categoryCount: { fontSize: 11, color: '#94A3B8', marginTop: 2 },

    // ── Sidebar ──
    sidebar: {
      flex: isMobile ? 1 : 0.4,
      minWidth: isMobile ? '100%' : 300,
    },
    sidebarPromoImage: {
      width: '100%',
      height: isMobile ? 180 : 220,
      borderRadius: 16,
      overflow: 'hidden',
      marginBottom: 16,
      backgroundColor: '#EFF6FF',
    },
    sidebarImage: { width: '100%', height: '100%' },
    sidebarImagePlaceholder: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#EFF6FF',
    },
    sidebarImageText: { color: '#2563EB', fontSize: 16, fontWeight: '600' },
    sidebarPromo: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: 20,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: '#E2E8F0',
    },
    sidebarPromoTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: '#0F172A',
      marginBottom: 10,
    },
    sidebarPromoText: {
      fontSize: 14,
      color: '#64748B',
      lineHeight: 20,
      marginBottom: 16,
    },
    sidebarPromoButton: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      backgroundColor: '#0F172A',
      borderRadius: 10,
      alignSelf: 'flex-start',
    },
    sidebarPromoButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' },
    sidebarFeatures: { gap: 12, marginBottom: 16 },
    sidebarFeature: {
      flexDirection: 'row',
      gap: 12,
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: '#E2E8F0',
    },
    sidebarFeatureIcon: { fontSize: 24 },
    sidebarFeatureContent: { flex: 1 },
    sidebarFeatureTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: '#0F172A',
      marginBottom: 4,
    },
    sidebarFeatureText: { fontSize: 13, color: '#64748B', lineHeight: 18 },
    sidebarNewsletter: {
      backgroundColor: '#0F172A',
      borderRadius: 16,
      padding: 24,
    },
    sidebarNewsletterTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: '#FFFFFF',
      marginBottom: 8,
    },
    sidebarNewsletterSubtitle: {
      fontSize: 14,
      color: 'rgba(255,255,255,0.7)',
      marginBottom: 16,
    },
    sidebarNewsletterForm: { gap: 10 },
    sidebarNewsletterInput: {
      backgroundColor: '#FFFFFF',
      borderRadius: 10,
      paddingVertical: 12,
      paddingHorizontal: 14,
      fontSize: 14,
      color: '#0F172A',
    },
    sidebarNewsletterButton: {
      paddingVertical: 12,
      paddingHorizontal: 20,
      backgroundColor: '#2563EB',
      borderRadius: 10,
      alignItems: 'center',
    },
    sidebarNewsletterButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' },
    sidebarHeader: { marginBottom: 16 },
    sidebarTitle: { fontSize: 18, fontWeight: '700', color: '#0F172A' },
    tabContainer: { flexDirection: 'row', gap: 8, marginBottom: 20 },
    tab: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 10,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E2E8F0',
    },
    tabActive: { backgroundColor: '#0F172A', borderColor: '#0F172A' },
    tabText: { fontSize: 13, color: '#64748B', fontWeight: '500' },
    tabTextActive: { color: '#FFFFFF', fontWeight: '600' },
    sidebarLoading: { padding: 20, alignItems: 'center' },
    articleList: { gap: 16 },
    articleItem: {
      flexDirection: 'row',
      gap: 12,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#E2E8F0',
    },
    articleThumbnail: {
      width: 56,
      height: 56,
      borderRadius: 12,
      backgroundColor: '#EFF6FF',
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
    },
    articleThumbnailImage: { width: '100%', height: '100%' },
    articleThumbnailText: { color: '#2563EB', fontSize: 16, fontWeight: '700' },
    articleInfo: { flex: 1, justifyContent: 'center' },
    articleTitle: { fontSize: 14, fontWeight: '600', color: '#0F172A', marginBottom: 4 },
    articleCategory: { fontSize: 12, color: '#94A3B8' },

    // ── Entertainment / Featured ──
    entertainmentSection: { marginBottom: 48 },
    articlesGrid: {
      flexDirection: isMobile ? 'column' : 'row',
      gap: 16,
      flexWrap: 'wrap',
    },
    articleCard: {
      ...(isMobile ? { flex: 1 } : {}),
      ...(Platform.OS === 'web' && !isMobile
        ? { width: (isDesktop ? 'calc(33.333% - 11px)' : 'calc(50% - 8px)') as any }
        : {}),
      minWidth: isMobile ? '100%' : 280,
      maxWidth: isMobile ? '100%' : 380,
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: '#E2E8F0',
      ...(Platform.OS === 'web'
        ? { boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.04)' }
        : { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 3, elevation: 2 }),
    },
    articleImage: { width: '100%', height: 180 },
    articleImagePlaceholder: {
      height: 180,
      backgroundColor: '#EFF6FF',
      justifyContent: 'center',
      alignItems: 'center',
    },
    articleImageText: { color: '#2563EB', fontSize: 16, fontWeight: '600' },
    articleCardContent: { padding: 16 },
    articleCardTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: '#0F172A',
      marginBottom: 8,
    },
    articleCardMeta: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    articleCardPrice: { fontSize: 15, fontWeight: '700', color: '#0F172A' },
    articleCardRating: { fontSize: 13, color: '#64748B' },

    // ── Featured section ──
    featuredSection: {
      flexDirection: isMobile ? 'column' : 'row',
      gap: 16,
      marginBottom: 48,
    },
    featuredCard: {
      flex: 2,
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: '#E2E8F0',
    },
    featuredImageContainer: {
      position: 'relative',
      height: isMobile ? 200 : 300,
      backgroundColor: '#EFF6FF',
    },
    featuredTag: {
      position: 'absolute',
      top: 16,
      right: 16,
      backgroundColor: '#0F172A',
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 8,
      zIndex: 1,
    },
    featuredTagText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: '600',
    },
    featuredImage: { width: '100%', height: '100%' },
    featuredImagePlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    featuredImageText: { color: '#2563EB', fontSize: 18, fontWeight: '600' },
    featuredContent: { padding: isMobile ? 16 : 24 },
    featuredTitle: {
      fontSize: isExtraSmall ? 18 : isMobile ? 20 : 28,
      fontWeight: '700',
      color: '#0F172A',
      marginBottom: 12,
    },
    featuredDescription: {
      fontSize: 15,
      color: '#64748B',
      lineHeight: 22,
      marginBottom: 16,
    },
    featuredMeta: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    featuredPrice: { fontSize: 20, fontWeight: '700', color: '#0F172A' },
    featuredRating: { fontSize: 14, color: '#64748B' },
    exploreButton: {
      alignSelf: 'flex-start',
      paddingVertical: 12,
      paddingHorizontal: 24,
      backgroundColor: '#0F172A',
      borderRadius: 10,
    },
    exploreButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' },

    // ── Events ──
    eventsSection: { marginBottom: 48 },
    eventsContent: { marginTop: 16 },
    eventsDescription: {
      fontSize: 15,
      color: '#64748B',
      lineHeight: 22,
      marginBottom: 24,
      textAlign: 'center',
    },
    eventsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
    eventCard: {
      flex: isMobile ? 1 : 1,
      minWidth: isMobile ? '100%' : 280,
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: '#E2E8F0',
      ...(Platform.OS === 'web'
        ? { boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.04)' }
        : { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 3, elevation: 2 }),
    },
    eventCardImage: { width: '100%', height: 180 },
    eventCardImagePlaceholder: {
      width: '100%',
      height: 180,
      backgroundColor: '#EFF6FF',
      justifyContent: 'center',
      alignItems: 'center',
    },
    eventCardImageText: { color: '#2563EB', fontSize: 16, fontWeight: '600' },
    eventCardContent: { padding: 16 },
    eventCardTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: '#0F172A',
      marginBottom: 6,
    },
    eventCardCategory: { fontSize: 13, color: '#94A3B8' },
    emptyText: { textAlign: 'center', color: '#94A3B8', fontSize: 14, padding: 20 },

    // ── About ──
    aboutSection: { marginBottom: 48 },
    aboutContent: { marginTop: 16 },
    aboutText: {
      fontSize: 15,
      color: '#64748B',
      lineHeight: 24,
      marginBottom: 32,
      textAlign: 'center',
    },
    aboutFeatures: { flexDirection: isMobile ? 'column' : 'row', gap: 16, flexWrap: 'wrap' },
    aboutFeature: {
      flex: isMobile ? 1 : 1,
      minWidth: isMobile ? '100%' : 250,
      alignItems: 'center',
      padding: 24,
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E2E8F0',
    },
    aboutFeatureIcon: { fontSize: 48, marginBottom: 16 },
    aboutFeatureTitle: {
      fontSize: 17,
      fontWeight: '600',
      color: '#0F172A',
      marginBottom: 8,
      marginTop: 12,
    },
    aboutFeatureText: {
      fontSize: 14,
      color: '#64748B',
      textAlign: 'center',
      lineHeight: 20,
    },

    // ── Contact ──
    contactSection: { marginBottom: 48 },
    contactContent: { marginTop: 16 },
    contactDescription: {
      fontSize: 15,
      color: '#64748B',
      lineHeight: 22,
      marginBottom: 32,
      textAlign: 'center',
    },
    contactInfo: {
      flexDirection: isMobile || isMobileWeb ? 'column' : 'row',
      gap: 16,
      marginBottom: 32,
      flexWrap: 'wrap',
    },
    contactItem: {
      flex: 1,
      minWidth: isMobile || isMobileWeb ? '100%' : 200,
      alignItems: 'center',
      padding: 24,
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E2E8F0',
    },
    contactIcon: { fontSize: 32, marginBottom: 12 },
    contactLabel: {
      fontSize: 13,
      fontWeight: '500',
      color: '#94A3B8',
      marginBottom: 6,
      marginTop: 10,
    },
    contactValue: {
      fontSize: 15,
      fontWeight: '600',
      color: '#0F172A',
      textAlign: 'center',
    },
    contactButton: {
      alignSelf: 'center',
      paddingVertical: 14,
      paddingHorizontal: 32,
      backgroundColor: '#0F172A',
      borderRadius: 10,
    },
    contactButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '600' },

    // ── CTA ──
    ctaSection: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: isMobile ? 32 : 48,
      alignItems: 'center',
      marginBottom: 48,
      borderWidth: 1,
      borderColor: '#E2E8F0',
    },
    ctaTitle: {
      fontSize: isExtraSmall ? 22 : isMobile ? 26 : 32,
      fontWeight: '700',
      color: '#0F172A',
      marginBottom: 12,
      textAlign: 'center',
    },
    ctaDescription: {
      fontSize: 15,
      color: '#64748B',
      marginBottom: 28,
      textAlign: 'center',
    },
    ctaButtons: {
      flexDirection: isMobileWeb ? 'column' : 'row',
      gap: 12,
      width: isMobileWeb ? '100%' : 'auto',
    },
    ctaButtonPrimary: {
      paddingVertical: 14,
      paddingHorizontal: 32,
      backgroundColor: '#0F172A',
      borderRadius: 10,
      width: isMobileWeb ? '100%' : 'auto',
    },
    ctaButtonSecondary: {
      paddingVertical: 14,
      paddingHorizontal: 32,
      backgroundColor: '#FFFFFF',
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      width: isMobileWeb ? '100%' : 'auto',
    },
    ctaButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '600',
      textAlign: 'center',
    },
    ctaButtonTextSecondary: {
      color: '#334155',
      fontSize: 15,
      fontWeight: '600',
      textAlign: 'center',
    },
    loadMoreButton: {
      marginTop: 24,
      paddingVertical: 12,
      paddingHorizontal: 28,
      backgroundColor: '#0F172A',
      borderRadius: 10,
      alignSelf: 'center',
    },
    loadMoreButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' },

    // ── Footer ──
    footer: {
      backgroundColor: '#0F172A',
      paddingTop: isMobile || isMobileWeb ? 40 : 56,
      paddingBottom: isMobile || isMobileWeb ? 24 : 32,
      paddingHorizontal: px,
    },
    footerContent: {
      flexDirection: isMobile || isMobileWeb ? 'column' : 'row',
      justifyContent: 'space-between',
      gap: isMobile || isMobileWeb ? 32 : 40,
      marginBottom: isMobile || isMobileWeb ? 24 : 32,
      maxWidth: maxW,
      alignSelf: 'center',
      width: '100%',
    },
    footerColumn: {
      flex: 1,
      minWidth: isMobile || isMobileWeb ? '100%' : 160,
    },
    footerColumnTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: '#FFFFFF',
      marginBottom: 16,
      letterSpacing: 0.3,
    },
    footerLink: {
      fontSize: 14,
      color: 'rgba(255,255,255,0.6)',
      marginBottom: 10,
      ...(Platform.OS === 'web' && { cursor: 'pointer' }),
    },
    qrCodeContainer: { alignItems: 'center', marginTop: 8 },
    qrCode: {
      width: isMobile || isMobileWeb ? 120 : 140,
      height: isMobile || isMobileWeb ? 120 : 140,
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      padding: 8,
      marginBottom: 10,
    },
    qrCodeLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: '#FFFFFF',
      marginBottom: 4,
      textAlign: 'center',
    },
    qrCodeSubLabel: {
      fontSize: 11,
      color: 'rgba(255,255,255,0.5)',
      marginBottom: 10,
      textAlign: 'center',
    },
    downloadButton: {
      backgroundColor: '#2563EB',
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 10,
    },
    downloadButtonText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '600',
      textAlign: 'center',
    },
    footerBottom: {
      borderTopWidth: 1,
      borderTopColor: 'rgba(255,255,255,0.1)',
      paddingTop: 20,
      alignItems: 'center',
      maxWidth: maxW,
      alignSelf: 'center',
      width: '100%',
    },
    footerText: { color: 'rgba(255,255,255,0.5)', fontSize: 13 },

    // ── Modals ──
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: Platform.OS === 'web' ? 20 : 16,
      ...(Platform.OS === 'web'
        ? { position: 'fixed' as any, top: 0, left: 0, right: 0, bottom: 0 }
        : {}),
    },
    modalContent: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      width: Platform.OS === 'web' ? '90%' : '100%',
      maxWidth: isMobile ? screenWidth - 32 : 520,
      maxHeight: Platform.OS === 'web' ? ('90vh' as any) : '90%',
      overflow: 'hidden',
      position: 'relative',
      ...(Platform.OS === 'web'
        ? { boxShadow: '0 8px 24px rgba(0,0,0,0.06)' }
        : { shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 16, elevation: 6 }),
    },
    modalScrollView: { flex: 1 },
    modalScrollContent: { flexGrow: 1, paddingBottom: 20 },
    modalCloseButton: {
      position: 'absolute',
      top: 12,
      right: 12,
      zIndex: 10,
      padding: 8,
      backgroundColor: '#F1F5F9',
      borderRadius: 20,
      width: 36,
      height: 36,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalCloseIcon: {
      fontSize: 18,
      color: '#64748B',
      fontWeight: 'bold',
    },
    modalPlaceholder: { padding: 40, alignItems: 'center' },
    modalPlaceholderText: {
      fontSize: 15,
      color: '#64748B',
      marginBottom: 20,
      textAlign: 'center',
    },
    modalButton: {
      backgroundColor: '#0F172A',
      paddingVertical: 12,
      paddingHorizontal: 24,
      borderRadius: 10,
    },
    modalButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '600' },

    // ── Hamburger / Mobile menu ──
    hamburgerButton: { padding: 8 },
    hamburgerLine: {
      width: 20,
      height: 2,
      backgroundColor: '#0F172A',
      marginVertical: 3,
      borderRadius: 1,
    },
    mobileMenuOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.3)',
      zIndex: 999,
    },
    mobileMenu: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      width: Math.min(280, screenWidth * 0.8),
      backgroundColor: '#FFFFFF',
      paddingTop: 60,
      paddingHorizontal: 24,
      zIndex: 1000,
      ...(Platform.OS === 'web'
        ? { boxShadow: '-4px 0 16px rgba(0,0,0,0.08)' }
        : { shadowColor: '#000', shadowOffset: { width: -4, height: 0 }, shadowOpacity: 0.08, shadowRadius: 16, elevation: 10 }),
    },
    mobileMenuItem: {
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: '#F1F5F9',
    },
    mobileMenuItemActive: {},
    mobileMenuText: { fontSize: 15, color: '#64748B', fontWeight: '500' },
    mobileMenuTextActive: { color: '#0F172A', fontWeight: '600' },
    mobileMenuClose: { position: 'absolute', top: 16, right: 16, padding: 8 },
    mobileMenuCloseText: { fontSize: 24, color: '#64748B' },
  });
};
